### ISSUE TITLE
Queue feature, compile error - Dynimical Library issue.

### ISSUE THREAD

**Issue by Darma** [spark/firmware#1018]
Hi,

I am working around to use Queue-ing feature of the Photon Firmware, from both [latest](https://github.com/spark/firmware/tree/latest) and [development](https://github.com/spark/firmware/tree/89029fb0faf4b7b6cfe91543181d457a0e24c572) branch.

For example:
```Cpp
os_queue_t my_queue; 
os_queue_create( &my_queue, 10, 10);
```
when compile I get following error message:

```
.. undefined reference to `os_queue_create'`
```
It seems like the source code is already in the relevant files: 

> /firmware/hal/inc/concurrent_hal.h 
> /firmware/hal/src/stm32f2xx/concurrent_hal.cpp

But it looks like it's not implemented (linked) in the dynamical library  `hal_dynalib_concurrent.h` file. At least current [development branch](https://github.com/spark/firmware/blob/89029fb0faf4b7b6cfe91543181d457a0e24c572/hal/inc/hal_dynalib_concurrent.h).  
> /firmware/hal/inc/hal_dynalib_concurrent.h

**Question:**
- How can or do I use Queue (os_queue*)  functions?

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by m-mcgowan** [comment]
Thanks for bringing this up! At present the queues are intended only for use by the system, since it's quite a low-level interface. I can add that low-level interface to the dynalib for the 0.6.0 release, and then we'll add a high-level wiring `Queue` interface for 0.7.0

**Comment by m-mcgowan** [comment]
Please see the PR above - you can pull that into your local working copy. Then recompile system-part2 and flash that to your device, then recompile the app and the low-level queue interface will be available.

**Comment by Darma** [comment]
Hey thanks, when will 0.6.x released? Any time estimation?

**Comment by aeris-ming** [comment]
Please update document If you guys do not want to export Free RT-OS API.
My suggestion is follow GUN style not stupid Aduino.
