### ISSUE TITLE
when flashing an invalid firmware binary (that the device ignores) it should post an event describing why the binary was not applied

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#1032]
E.g. flashing system binaries in the wrong order, or flashing a binary with an invalid CRC.

The event will help provide some visibility into the system, and help troubleshoot cases when binaries are not being applied, and conversely for success cases, will provide confirmation that a flashed binary will be applied on next reboot.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by technobly** [comment]
Spec from a discussion we had about this issue:

- publish an event when the system has rx'd an OTA image
    - success (include parseable module info)
    - failure (reason crc, module dependency (include parseable module info), wrong device type)
    - publish to cloud or reply to YMODEM host
- add to reset syndrome for when the system reboots and applies an OTA image
- HELLO message contains OTA_FLASHED_Status_SysFlag, so theoretically the cloud already knows if an OTA update was applied, and can generate an event based on this.
