### ISSUE TITLE
[electron] system-part3 module 

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#1033]
System part2 on electron is filling up quickly (so is part1.) There is room in the Electron for a system part3.

To free up room in system part 2, we can move functionality from part 2 to part 3. Since old code will be dynamically linking to part 2, we still need to provide the dynamic link interface in part 2, but the implementation can simply be stubs that call corresponding functions that have moved over to part 3.

We may also want to do the same for system part 1 - move over functionality from part 1 to part 3. Because of this, part 3 will be a dependency of part 1, and the correct flash order will be part 3, part 1, part 2.   

Since this isn't intuitive, we will rename the system parts, so that they are flashed in order part 1, part 2, part 3, and provide an updated memory map.  The renaming will be done in the `modules/electron` directory in the build:

- part1 -> part2
- part2 -> part3
- and a new part1 added that contains the new code.

Since it's just a rename of the module - the code is the same so the internal identifiers are the same, and the memory locations are the same. 

- part2: 0x8020000  (depends on part1)
- part3: 0x8040000  (depends on part2)
- part1: 0x8060000

So the only users that see the non-sequentialness of the address layout are those using dfu-util to directly flash firmware, and our documentation will include clear warnings of the address changes. If a dfu-util user flashes things in the wrong order, the device won't boot, but will still present DFU mode so that the flash can be re-done in the correct order. 

Casual users flashing via OTA or OTW via serial execute the flash steps in order - part1, part2, part3. (If they flash out of order, the device ignores the new module. An event will make this process more visible. #1032.)

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by technobly** [comment]
Present in v0.6.0-rc.1
