### ISSUE TITLE
gcc virtual device runs at 100% cpu

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#1036]
The gcc virtual device emulates an embedded device, where the CPU is being given work to do all the time. This carries over to the cross compiled version, where it consumes 100% of the executing cpu core on a desktop machine.

Some steps to mitigate this will make the cross compile device more scalable and environmentally friendly.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by sergeuz** [comment]
As a simple solution we can try to call `std::this_thread::yield()` before reentering busy loops, such as the application loop. Probably this can be even automated via gcc's instrumentation.

**Comment by joegoggins** [comment]
A non firmware way to do this is to run a gcc virtual device in a Docker container and specify the `--cpu-shares` (relative CPU shares)`, `--cpu-period`, or `--cpuset-cpus` flags to the [docker run command](https://docs.docker.com/engine/reference/run/) to limit how much CPU it consumes.

**Comment by andyw-lala** [comment]
That's just going to slow down the instance running in the container. It
will solve the host resource problem of pegging a core, but it will make
the instance run strangely as it meters the cpu out to the container.

On Wed, Jun 15, 2016 at 5:56 PM, Joe Goggins <notifications@github.com>
wrote:

> A non firmware way to do this is to run a gcc virtual device in a Docker
> container and specify the --cpu-shares (relative CPU shares),--cpu-period,
> or--cpuset-cpus` flags to the docker run command
> <https://docs.docker.com/engine/reference/run/> to limit how much CPU it
> consumes.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/spark/firmware/issues/1036#issuecomment-226344128>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ADv7QNGzv9q9_ib8DkejzEtKCE0WDdDkks5qMIMvgaJpZM4I22rg>
> .
>



-- 
Andy

**Comment by hazeem1991** [comment]
i really having like this kind of problem but i did not find any way to solve it any advice ?

**Comment by joegoggins** [comment]
The referenced [PR above provides a solution](https://github.com/particle-iot/device-os/pull/1167) and more advice @hazeem1991
