### ISSUE TITLE
Photon stuck on RED ( SOS) code

### ISSUE THREAD

**Issue by bert269** [spark/firmware#1039]
My device was working well, firmware 0.5.0.
 I made a minor change to the code to disable the LED (since the application I want to use it for cannot have the 'breathing LED all the time). I compiled and flashed the code to the Photon. It rebooted and immediately start the SOS sequence of flashes. Very hard to tell the amount of red flashes to determine what is going on.

I cannot seem to get out of this state, even after I reflashed the latest firmware in DFU mode, it flashes white once and immediately goes back to SOS.
I can only get it into DFU mode, nothing else. No other colors, only a brief white, followed by red or yellow color in DFU mode.

Please advise 

Thanks 

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by monkbroc** [comment]
Hi Bert,

You're going to get better help figuring out the problem in your application and how to revive your Photon if you post to https://community.particle.io. GitHub is best for reporting issues or tracking new features in the Particle system firmware.

**Comment by m-mcgowan** [comment]
Sorry to hear of the problems. Did you find a solution for this?

**Comment by technobly** [comment]
Also please utilize https://support.particle.io if your issue has not been resolved yet.
