### ISSUE TITLE
Check that all network calls are done on the system thread

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#1040]
https://github.com/spark/firmware/issues/904 was due to a network function being called on the application thread. Let's audit the system firmware to check that all functions that perform network operations or modify system thread state are called on the system thread.

`System.keepAlive` seems suspect since it uses the `ProtocolFacade`.

---

Completeness:
- [x] Photon network calls reviewed
- [x] Electron network calls reviewed

**Comment by m-mcgowan** [comment]
Any code that is run on the system thread that is not threadsafe, should only ever run on the system thread. This typically means any calls to those functions are wrapped in the SYSTEM_THREAD macro.

We might also consider adding macros to the functions themselves that validate they are run on the correct thread in debug builds, so mistakes can be caught.

**Comment by m-mcgowan** [comment]
Some possible approaches:
- get a static analysis of the call stack from the system loop
- get a static analysis of the call stack from all application API entrypoints (use the API testsuite, compiled against gcc.) Can validate all APIs are covered by using code coverage against the `wiring` module.
- if a method on the application thread also exists in the callchain of the system thread then we have a potential issue of calling thread-unsafe code from multiple threads.
