### ISSUE TITLE
Timer class wrapper for setting up interrups

### ISSUE THREAD

**Issue by zsup** [spark/firmware#105]
Some nice wrapped version of this? https://community.spark.io/t/creating-timer-based-interrupts/771/4

feature request from IRC

**Comment by m-mcgowan** [comment]
The Spark Interval Timer - https://github.com/pkourany/SparkIntervalTimer/ by @pkourany provides an interface for working with timers.

**Comment by pkourany** [comment]
@m-mcgowan, I believe we can do way better with a generalized HAL timer manager :)
