### ISSUE TITLE
Run event loop in delay on app thread only

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#1055]
I have an application running without system thread with the hardware logic running in a separate wiring `Thread` and only cloud related things in `loop()`.

When calling `delay()` in the hardware thread, it processes cloud events. Since the main thread also processes cloud events this leads to random crashes.

The workaround is to call `HAL_Delay_Milliseconds()`.

The fix is to ensure that `delay()` only processes cloud events when called on the main thread.

This issue applies with system thread enabled our disabled.

I'll add a test case when my internet comes back at home.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by m-mcgowan** [comment]
Let's try to work this through so the code is covered by a unit test that exercises the different cases/emulates different calling threads, as well as a suite of acceptance test apps to actually test the desired outcome for real. This is particularly difficult with the way the code is presently structured.
