### ISSUE TITLE
as a user, I can interrupt the blinking cyan cloud connection with the setup button

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#1067]
At present, pressing the setup button to enter listening mode, or a double tap to powerdown, doesn't interrupt the cloud connection process. (It does interrupt the network connection process.)

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (as of 0.5.3-rc.1)

**Comment by technobly** [comment]
Related to https://github.com/spark/firmware/issues/1013

**Comment by technobly** [comment]
@m-mcgowan just to clarify, does this apply to single-threaded mode as well... or just multi-threaded mode?

**Comment by m-mcgowan** [comment]
For both!

**Comment by sergeuz** [comment]
Let's put this on hold for now, since in case of Photon, there isn't an easy way to break a blocking call to the socket API other than shutting down WICED connectivity layer (and thus breaking lwIP processing loop), which is buggy in the WICED release that we currently use.

**Comment by technobly** [comment]
@sergeuz This would still be very useful for the Electron, which can sometimes have a long connection time, especially if the unit is encountering a handshaking issue.  The implementation for Electron could be stubbed out for Photon/P1 and revisited after WICED is updated.
