### ISSUE TITLE
[0.6.0-rc.1] Keyboard.print() outputs space instead of character

### ISSUE THREAD

**Issue by hramadan** [spark/firmware#1090]
Keyboard.print() outputs spaces instead of the characters in the parameter string, and looks to be one short, eg Keyboard.print("TEST"); will output " " (ie three spaces). 

System firmware version  0.6.0-rc.1 on PHOTON

void setup() {
    Keyboard.begin();
}
void loop() {
    // String of spaces seen
    Keyboard.print("String of characters expected");
    delay(5000L);
}

---

Completeness:
- [X] Minimum test case added
- [X] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by avtolstoy** [comment]
@hramadan This should be fixed in #1091.
