### ISSUE TITLE
Several people report problems with 0.6.0-rc.1 and default USB Serial

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#1108]
One thread
https://community.particle.io/t/6-0-serial-interface-issue/25483

Even if it's not a FW issue, people get rather confused!

Also a short episode in here 
https://community.particle.io/t/photon-sleep-mode-deep-waking-problems/25339/31

**Comment by technobly** [comment]
I'm guessing this will be resolved in 0.6.0-rc.2 with this PR https://github.com/spark/firmware/pull/1092  Note the advice on drivers.

**Comment by ScruffR** [comment]
The fix seems to be mainly targeting Windows, but the last post in my first link seems to deal with a Mac Book, so I'm not sure if that will be go away the same way.

**Comment by technobly** [comment]
Closing now that v0.6.0-rc.2 is out :)
