### ISSUE TITLE
[Core 0.5.3]: Interrupts are disabled by default

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#1136]
As discussed here, 0.5.3 seems to have introduced an unexpected behaviour with interrupts on Cores
https://community.particle.io/t/interrupts-disabled-on-core-fw-0-5-3-and-later/26393

Only after adding `interrupts();` they start firing.

``` cpp
void isr()
{
  digitalWrite(D7, !digitalRead(D7));
}

void setup() {
  pinMode(D7, OUTPUT);
  pinMode(D3, INPUT_PULLDOWN);
  attachInterrupt(D3, isr, CHANGE);
  //attachInterrupt(D3, isr, RISING);
  //attachInterrupt(D3, isr, FALLING);
  //interrupts();
}

void loop() { }
```

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by gmazzo** [comment]
I've spent three days thinking I was doing something wrong. In deed, add `interrupts();` did the trick. 

The docs says it's enabled by default, so it has to be an issue:
https://docs.particle.io/reference/firmware/core/#interrupts

**Comment by ScruffR** [comment]
Thanks for confirming 👍

**Comment by ScruffR** [comment]
It's a while now and still no Particle confirmation?
An new case where user got bitten by this still unaddressed issue
 https://community.particle.io/t/unable-to-get-results-from-dht22/28361

But there would be a simple cure (I guess)

**Comment by technobly** [comment]
Thanks for the great test case @ScruffR !

I can confirm this is working as expected on 0.5.2, and broken on 0.5.3 (requiring `interrupts();` for the ISR to fire).
