### ISSUE TITLE
String parser

### ISSUE THREAD

**Issue by zsup** [spark/firmware#114]
See this thread:

https://community.sparkdevices.com/t/rest-api-arguments-is-there-a-better-way/960/3

User story:
As a user, I want a simple method to parse strings so that I can more easily use Spark.function() without creating my own parser every time.

**Comment by m-mcgowan** [comment]
The community heard the call and answered! There are a few libraries in the community that address this:

![screenshot 2015-04-21 19 42 30](https://cloud.githubusercontent.com/assets/2465470/7258785/f5c44e9c-e85e-11e4-95a1-69f824204ff7.png)
