### ISSUE TITLE
e

### ISSUE THREAD

**Issue by sergethibault** [spark/firmware#1142]
< Please summarize your issue here.  Check [x] as many boxes below as you can before submitting your issue.  Thanks -- you rock! >

---

Completeness:
- [ ] Minimum test case added
- [ ] Device, system and user firmware versions stated
- [ ] Particle confirmed

**Comment by technobly** [comment]
"e" for error?  Closing... please edit your original post if it was not an error, thanks!

**Comment by sergethibault** [comment]
Sorry, created by error
