### ISSUE TITLE
Particle.publish with integer should fail

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#1194]
`Particle.publish` should only accept `String` data and error out when another data type is passed.

```
int value = 10;
Particle.publish("test", value);
```

This code compiles when it shouldn't because the `int` value is passed to the `PublishFlag` constructor and used in this overloaded method:
`    inline bool publish(const char *eventName, PublishFlag eventType=PUBLIC)`

The solution would be to prohibit implicit calls to the `PublishFlag` constructor. This should just be the `explicit` keyword right? Quick fix, but I don't currently have the time to try it out. Sorry.

---

Completeness:
- [X] Minimum test case added
- [x] Device, system and user firmware versions stated (0.6.0)

**Comment by avtolstoy** [comment]
Fixed by #1236, #1315, released in 0.7.0-rc.1
