### ISSUE TITLE
Hang in Build when selecting Library on Safari Mac.

### ISSUE THREAD

**Issue by kaspesla** [spark/firmware#1239]
I can add other libraries we tried, but when I click on ADAFRUIT_ST7735, I only get "Loading..." forever.
It works okay in Chrome. The issue seems to be only with Safari.

1) In Safari on Mac, create a new App in build
2) Click on Libraries
3) Search for ADAFRUIT_ST7735
4) Click on it.
5) Observe not-workingness

Mac OS X 10.11.6
Safari Version 9.1.3 
---

Completeness:
- [ ] Minimum test case added
- [ ] Device, system and user firmware versions stated
- [ ] Particle confirmed

**Comment by monkbroc** [comment]
Hang tight, we have a fix ready to deploy for this!

**Comment by kaspesla** [comment]
Good to hear! Thanks.
Not a show-stopper since it does work in Chrome.
-Ken

**Comment by monkbroc** [comment]
This is fixed now.
