### ISSUE TITLE
TCP Firmware sends ACKs and separate response for every Chunk in Fast OTA mode

### ISSUE THREAD

**Issue by brycekahle** [spark/firmware#1240]
In Fast OTA mode, the firmware should not respond to every Chunk message (especially because they are NON confirmable messages). To compensate for this, it should respond to the UpdateDone with whether it needs to request additional missed/invalid chunks. Those missing/invalid chunks are then requested via the ChunkMissed message.

The current firmware follows the correct procedure for requesting missing chunks in Fast OTA mode, but it **incorrectly [sends ACKs](https://github.com/spark/firmware/blob/dfdadfb3e3509bf3e98a28f64bd3917caca1ffa2/communication/src/spark_protocol.cpp#L1074) and [separate responses](https://github.com/spark/firmware/blob/dfdadfb3e3509bf3e98a28f64bd3917caca1ffa2/communication/src/spark_protocol.cpp#L1122) for each individual Chunk message**.

Firmware version: up to and including 0.6.1-rc.2
Device: Photon/P1/Core (any TCP device)

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by towynlin** [comment]
Actually I think the file `spark_protocol.cpp` is only used for the Core. I'm pretty sure the Photon, P1, and any other TCP device uses the `lightssl_message_channel`, `lightssl_protocol`, and then just like the DTLS firmware path, uses [ChunkedTransfer](https://github.com/spark/firmware/blob/dfdadfb3e3509bf3e98a28f64bd3917caca1ffa2/communication/src/chunked_transfer.cpp#L139) to manage OTA.

@m-mcgowan can you confirm/deny?

**Comment by avtolstoy** [comment]
@towynlin TCP devices still use `SparkProtocol`. See https://github.com/spark/firmware/blob/develop/communication/src/protocol_selector.h#L24

**Comment by towynlin** [comment]
Ah thanks Andrey. So... does nothing use lightssl*?

**Comment by avtolstoy** [comment]
Currently no :)

**Comment by towynlin** [comment]
LOL, OK, well then the path forward for working on this issue is clear! 😺
