### ISSUE TITLE
WiFi.connecting() returns `false` during DHCP resolve

### ISSUE THREAD

**Issue by technobly** [spark/firmware#1241]
### Given:

When a Wi-Fi device connects to a Wi-Fi AP, the system RGB LED will blink slow green while it connects to the router with it's credentials, and then fast green while DHCP is resolving.  After DHCP resolves the device has an IP address and `WiFi.ready()` will return `true`.

### Expected Behavior:

`WiFi.connecting()` returns `true` while Wi-Fi connection process is underway, and `false` after a successful connection is made.

### Problem:

`WiFi.connecting()` returns `false` while DHCP is resolving.

### Example:

```c++
SYSTEM_MODE(MANUAL);
SYSTEM_THREAD(ENABLED);

void setup() {
    pinMode(D7, OUTPUT);
    Particle.connect();
}

void loop() {
    // During a SLOW DHCP resolve, D7 will turn off briefly while the RGB is flashing fast green
    if (WiFi.connecting() || WiFi.ready()) {
        digitalWrite(D7, HIGH);
    }
    else {
        digitalWrite(D7, LOW);
    }
    Particle.process();
}
```

Thanks @suda !

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (0.6.1-rc.2)

**Comment by sergeuz** [comment]
@m-mcgowan What would be better, to make `WLAN_CONNECTING = 1` span over both AP connection and DHCP phases, or split `WLAN_DHCP` into two flags, e.g. `WLAN_DHCP_PENDING` and `WLAN_DHCP_DONE`?

**Comment by m-mcgowan** [comment]
I feel `WLAN_CONNECTING` should span the entire connection process since that's what is least surprising.

**Comment by suda** [comment]
![](https://media.giphy.com/media/11m0KYbHLWfFQY/giphy.gif)
