### ISSUE TITLE
Change default DHCP client name

### ISSUE THREAD

**Issue by brycekahle** [spark/firmware#1251]
The default is `WICED DHCP Client` which can cause problems with DHCP servers who also automatically add a DNS hostname because it contains spaces.

---

Completeness:
- [ ] Minimum test case added
- [x] Device, system and user firmware versions stated (as of 0.6.1)

**Comment by technobly** [comment]
@brycekahle Is the recommendation here just to remove the spaces from the name?  Also do you have a test case where we can verify this change would be successful?

**Comment by brycekahle** [comment]
Definitely remove the spaces. It might be nice to use something that makes it clear what device it is, say `ParticlePhoton`?

**Comment by avtolstoy** [comment]
What if we use device id as a default hostname? Sounds like a good option as well, considering device id is unique.

We should probably also add some setter/getter methods to modify hostname (e.g. `WiFi.get/setHostname()` or `System.get/setHostname()`)

**Comment by avtolstoy** [comment]
Implemented in #1296. Release in 0.7.0-rc.1.
