### ISSUE TITLE
How to kill a thread?

### ISSUE THREAD

**Issue by kenvernaillenvub** [spark/firmware#1268]
I use threads from 'spark_wiring_thread.h' to run 3 threads.
Is there a way to kill a thread or let all threads wait for current process to finish?

**Comment by avtolstoy** [comment]
You can wait for the thread to finish by using its `join()` function. You can also kill a running thread by using its `dispose()` method, but that's an unsafe operation that might cause instabilities or even a crash. It's better to introduce some kind of a flag or synchronization primitive to notify a running thread that you want it to exit.

**Comment by kenvernaillenvub** [comment]
Thanks
