### ISSUE TITLE
[Electron] Wire1 I2C requires work around configuring SCL pin before Wire1.begin();

### ISSUE THREAD

**Issue by technobly** [spark/firmware#1282]
### Expected behavior

1. Wire1 I2C works without configuring SCL and SDA pins ahead of time.  Currently as of 0.5.0 ~ 0.6.1 there is a work around to add `pinMode(C5, INPUT);` before `Wire1.begin();`. This is not required for 0.4.8-rc.6 firmware.

1. NACK Timeout of WIre1 and Wire should be identical since Wire1 is just an alternate GPIO location for the I2C bus.
 
1. Wire1 should be tested in hardware every firmware release.

### Observed behavior

1. When using Wire1 with the Electron, a hard fault is observed after flashing to the device.

1. Wire1 (C5, C4) NACK takes 100ms to timeout before STOP is generated, whereas Wire (D1, D0) NACK times out immediately.  (see attached scope images).

1. Current Wire1 is not tested in hardware on Electron each firmware release, only API tests.

### Steps to reproduce

Using 0.5.0 ~ 0.6.1 firmware, run the test app below and comment out the pinMode line.  Hard fault can only be observed if the pull up resistor on C5 is inserted.  With no Slave device, only the Slave address will be seen on the bus.

### Test App

```c
#include "Particle.h"

#define MY_WIRE Wire1

byte x = 0;

void setup() {
  // pinMode(C5, INPUT); // work around
  MY_WIRE.begin();
}

void loop() {
  MY_WIRE.beginTransmission(0x1A);
  MY_WIRE.write(x);
  MY_WIRE.endTransmission();
  x++;
  delay(500);
}
```

### References

https://community.particle.io/t/wire1-not-working/30913
https://docs.particle.io/reference/firmware/electron/#wire-i2c-

### Scope images

![wire](https://cloud.githubusercontent.com/assets/2249224/24371535/b769af3e-12f0-11e7-934f-e6dda352cbc2.png)

![wire1-1](https://cloud.githubusercontent.com/assets/2249224/24371541/bc5029ec-12f0-11e7-91e0-526ee128b98d.png)

![wire1-2](https://cloud.githubusercontent.com/assets/2249224/24371546/c06f6574-12f0-11e7-8591-cadbb85849d1.png)

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (using 0.5.0 ~ 0.6.1)

**Comment by avtolstoy** [comment]
Fixed in #1302, released in 0.7.0-rc.1
