### ISSUE TITLE
[Core] Software Timers throw error in /freertos4core/src/concurrent_hal.cpp

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#1284]
As discussed in this thread and tried to discuss on slack
https://community.particle.io/t/connecting-a-keypad-over-i2c/23736/18?u=scruffr

## Expected behavior
When building the TIMERS.ino example refered to by the [Core Reference Docs](https://docs.particle.io/reference/firmware/core/#software-timers), I would expect it to build.

## Observed behavior
It does not build.

## Steps to reproduce
Building in Web IDE or CLI against a Core targeting 0.6.1 it does not, but throws an 
`Error: Could not compile. Please review your code.`
No idea how the OP in the linked thread above got a different error
```
lib/freertos4core/src/concurrent_hal.cpp:113:38: error: 'xTaskIsTaskFinished' was not declared in this scope
while (xTaskIsTaskFinished(thread) != pdTRUE)
^
```

## Test App
https://build.particle.io/libs/freertos4core/0.2.0/tab/example/timers.ino

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by technobly** [comment]
Thanks @ScruffR, would you please update your bug report to use the same format as this one https://github.com/spark/firmware/issues/1281 ?

**Comment by technobly** [comment]
Thanks for the extra details @ScruffR!  I quickly attempted to verify this by using that example, and it compiled with 0.5.3, 0.6.0 and 0.6.1 so I can't confirm it.

Would you try something for me?  On the one you created, can you change one line in your example timers.ino (just add a new blank line) save it, and try compiling again.  Does that fix it?  I think there is still a known bug where trying to compile before all of the library files are copied over will result in an error.  If you encounter that you have to change the app again to have it retry including all of the files again.

**Comment by technobly** [comment]
Trying my own advice, I tried to copy and compile quickly and it failed.  Then tried to add one line, save.  It still did not compile.  BUT, when I removed the library, added it back to the app, waited a few... then compiled and it worked fine.  So this is likely a bug to report at https://github.com/spark/cloud but I'm sure I've logged this already internally.  I'll link to this issue as well.  Please close if you can confirm this is not a firmware issue, but rather a Web IDE issue.

**Comment by ScruffR** [comment]
@technobly, yup that worked, but this way, we'd have to search for another cause/solution for the member in the linked thread.
