### ISSUE TITLE
Add panic define from environment variable

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#131]
From @davids5 here:
https://community.spark.io/t/bug-bounty-kill-the-cyan-flash-of-death/1322/408?u=zachary

> It would be good to add it in the toplevel makefile (like the USE_SWD_JTAG) and have a set of switches in the webIDE for Release / Debug (in debug add the debug_ouput code to sketch), USE_SW_JATAG and VERBOSE_PANIC. For the sort term this is need because the WD will kill PANIC before it will flahs the code so seeing the text will help a user debug and out of heap error

**Comment by m-mcgowan** [comment]
This isn't an issue anymore - the watchdog is notified during the Panic LEDs.
