### ISSUE TITLE
Fix Delay_Microsecond() wrapping issue

### ISSUE THREAD

**Issue by satishgn** [spark/firmware#133]
I am working on this currently.
Idea is to reset the DWT cycle counter in the function call before doing the delay.
		//Reset DWT cycle counter register
		CoreDebug->DEMCR |= CoreDebug_DEMCR_TRCENA_Msk;
		DWT->CYCCNT = 0;
		DWT->CTRL |= DWT_CTRL_CYCCNTENA_Msk;

**Comment by m-mcgowan** [comment]
Resolved. micros() uses the full 32-bit range.
