### ISSUE TITLE
Fresh install for local build fails with ARM gcc version 5.3.1 or later required

### ISSUE THREAD

**Issue by gjt211** [spark/firmware#1366]
I followed the guide  from here
[https://github.com/spark/firmware/blob/latest/docs/gettingstarted.md](url)
to setup a local build environment on my mac.

I also followed the dependancy requirements from here [https://github.com/spark/firmware/blob/latest/docs/dependencies.md#1-download-and-install-dependencies](url)

I then entered the following `make clean all PLATFORM=photon -s program-dfu` as described and the result was;

```
../build/arm-tools.mk:42: *** "ARM gcc version 5.3.1 or later required, but found 4.9.3".  Stop.
```
I am really confused, the guide even requested a check to make sure I am using 4.9.3, so what is going on here?
Do I need to update my ARM gcc version, and if so, how do I do that?

**Comment by avtolstoy** [comment]
@gjt211,

GCC 5.3.1 is a requirement starting with 0.7.0-rc.1 (it is a requirement for the `develop` branch as well). The getting started and dependencies documentation you've linked are from the `latest` branch, which is currently 0.6.2. If you are seeing the error about 5.3.1, you are probably trying to build either develop or 0.7.0-rc.X branch.

Please check the dependencides.md from `develop` branch https://github.com/spark/firmware/blob/develop/docs/dependencies.md for the 5.3.1 GCC download links.

Generally ARM GCC releases can be found at https://developer.arm.com/open-source/gnu-toolchain/gnu-rm/downloads
