### ISSUE TITLE
Find out why after call Particle.connect() lost control of RX/TX pin,Is there a Document list all configurations?

### ISSUE THREAD

**Issue by aeris-ming** [spark/firmware#1431]
Find Macro define #define USE_SERIAL1 1 in ./system/src/wifitester.cpp
Is there any Doc list all configure about Pins
It is very dispirited after wast days on that issue.
Please Please send me the configure Doc link Thanks!

**Comment by m-mcgowan** [comment]
The WiFi tester code is only enabled on entering listening mode, and only if the app has `System.enable(SYSTEM_FLAG_WIFITESTER_OVER_SERIAL1)`.

Could you provide a test application that shows the problem you are seeing?

**Comment by aeris-ming** [comment]
Sorry,I made a mistake.

#if Wiring_WiFi
System.enable(SYSTEM_FLAG_WIFITESTER_OVER_SERIAL1);
#endif

I think I do not define Wiring_WiFi,Maybe it is defined in some header.
