### ISSUE TITLE
Request for new USB Product IDs from openmoko.org

### ISSUE THREAD

**Issue by satishgn** [spark/firmware#161]
Before integrating the feature/usb-hid-support branch into master, we require new product IDs for the following HID support in core-firmware:
1)Spark Core Arduino-compatible board with WiFi (Mouse)
2)Spark Core Arduino-compatible board with WiFi (Keyboard)

**Comment by m-mcgowan** [comment]
@satishgn - since we have acquired our own vendor ID, this issue can be closed?

**Comment by m-mcgowan** [comment]
We have our own vendor ID.
