### ISSUE TITLE
Provide flash disk drive USB-MSD(Mass storage device) support

### ISSUE THREAD

**Issue by satishgn** [spark/firmware#166]
Similar to USB-CDC & USB-HID, USB-MSD feature should be conditionally compiled.

**Comment by m-mcgowan** [comment]
Closing this to help focus on priority issues . If it becomes a requirement later we can re-open it.

**Comment by atwalsh** [comment]
I'm interested in this feature as well. I saw a [question][1] on the forums, is there a chance this will be implemented?

[1]: https://community.particle.io/t/how-to-use-the-stm32f205-usb-in-photon-as-a-usb-msc-device-or-a-usb-audio-speaker-device/29298/4
