### ISSUE TITLE
UDP parsePacket() and available() not working as expected

### ISSUE THREAD

**Issue by pkourany** [spark/firmware#170]
After some researching on the Arduino ethernet implementation of UDP and comments from pbs777 , it has been found that the Spark versions of UDP parsepacket() and available() are not functioning as expected.

The Arduino version of parsepacket() extracts the IP, source port and UDP data field length from a received packet. So parsepackate() returns the length of the data field of a "new"  UDP packet as any old packet data is flushed first.  The Arduino version of available() returns the UDP packet data length field after the parsepacket() call and reduces by 1 as bytes are read from the UDP packet buffer.

The Spark version of parsePacket() returns the length of the entire UDP receive buffer, not just the next complete UDP packet which is inconsistent both with its implied and documented description.  The Spark version of available() again reports on the entire receive UDP buffer, not the currently parsed UDP packet.  Both functions need to be revised accordingly.

**Comment by m-mcgowan** [comment]
When I checked with a simple UDP client with the latest 1.14 cc3000 patch, I was seeing the correct packet sizes being delivered (simple strings, length 42.) 

Marking this as resolved, we can open up again if the issue returns.
