### ISSUE TITLE
Add Arduino binary literal syntax

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#171]
Issue raised in [hardware repo](https://github.com/spark/core/issues/49) belongs here.

In Arduino you can define binary values with B, e.g. "B10011".

See code: https://code.google.com/p/arduino/source/browse/trunk/hardware/arduino/cores/arduino/binary.h

use case: http://arduino.cc/en/Reference/LiquidCrystalCreateChar

**Comment by m-mcgowan** [comment]
Unfortunately, this is a (non-standard) feature of the avr compiler, that isn't supported in gcc, so supporting this is not possible unless we preprocess all source files (no small undertaking.) The ideal fix for this is to document the different syntax. cc: @kennethlimcp

**Comment by technobly** [comment]
Implemented in https://github.com/spark/firmware/pull/1191 released in 0.6.1-rc.2.
