### ISSUE TITLE
Create Eclipse Coding Style Formatter for auto fomatting source files

### ISSUE THREAD

**Issue by satishgn** [spark/firmware#19]
Coding style ideas are welcome such as use of double space instead of tabs for new line etc....

**Comment by m-mcgowan** [comment]
We're standardizing on 4-space tabs. The normal reason folks cite for wanting smaller tabs is so they can have deeper nesting. In that case, the ideal solution is to refactor the code into smaller functions to avoid the need for such deep nesting (and hard-to-read code).  Just sayin'! :-)

**Comment by m-mcgowan** [comment]
We are now using a handful of different tools for editing text, NetBeans, Eclipse, Sublime, vim, to name a few. This issue has been dormant for 2 years so closing. We can re-open a new one when we have a clearer picture on what needs to be standardised and how we enforce it.
