### ISSUE TITLE
Separate constant parts of PIN_MAP [memory optimization]

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#192]
Symbols sorted by the amount of RAM they take up can be found with:

    arm-none-eabi-nm --size-sort core-firmware.elf | grep -i " [bd] "

With the current (May 9th) master build, the 6th largest item in the list is [`PIN_MAP`](https://github.com/spark/core-firmware/blob/master/src/spark_wiring.cpp#L58), taking 0x1F8 = 504 bytes. That's an array of 21 `STM32_Pin_Info` structs, each occupying 24 bytes (23 + 1 alignment byte apparently).

Much of `PIN_MAP` never changes and could be declared `const`, moving it from RAM to flash. A quick glance at the (not necessarily exhaustive) output of:

    grep -rn "PIN_MAP.* = " src

indicates that only the `pin_mode`, `timer_ccr`, and `user_property` change. That's 10 bytes per `STM32_Pin_Info` struct that is actually variable. The rest (13 bytes) could probably be pulled out into a separate data structure that is declared `const`. If that's true, it could free up to 294 bytes for use by users.

**Comment by m-mcgowan** [comment]
Before optimization

   text	   data	    bss	    dec	    hex	filename
  79088	   1100	   9044	  89232	  15c90	../build/target/main/platform-0/main.elf

ram = 10144

after

   text	   data	    bss	    dec	    hex	filename
  79384	    596	   9212	  89192	  15c68	../build/target/main/platform-0/main.elf

ram = 9808

Saves 336 bytes.

**Comment by m-mcgowan** [comment]
Unsure if this fix should be applied. I'm inclined to say no, and that flash space is more important for some than ram (and we have freed up lots of ram lately.)
