### ISSUE TITLE
time_t should be unsigned  (UINT32) instead of signed

### ISSUE THREAD

**Issue by pkourany** [spark/firmware#214]
Arduino libraries define time_t as UNSIGNED LONG.  The Core firmware defines time_t as INT32.  From wikipedia:

"Unix and POSIX-compliant systems implement the time_t type as a signed
  integer (typically 32 or 64 bits wide) which represents the number of seconds since the start of the Unix epoch: midnight UTC of January 1, 1970 (not counting leap seconds). Some systems correctly handle negative time values, while others do not. Systems using a 32-bit time_t type are susceptible to the Year 2038 problem."

Unless the Core firmware handles negative time, it is recommend that time_t be defined as UINT32 (unsigned long) to avoid the Year 2038 issue.

**Comment by m-mcgowan** [comment]
With the separation of platform-specifics and system code, `time_t` comes from the system headers. (which is better than getting the value from the cc3000 drivers.) However, it's still defined as a signed value afaict.

**Comment by m-mcgowan** [comment]
we can't really change `time_t` since this is part of the system headers. However, we can change the `Time` class to use the `systick_t` which is unsigned.

**Comment by m-mcgowan** [comment]
Our hands are tied, since the type is provided by the runtime library.
