### ISSUE TITLE
Ram Enhancement

### ISSUE THREAD

**Issue by fearless40** [spark/firmware#217]
In the file spark_utilities.h you can drop ram usage by about 256 bytes. (4 x 64) 
struct User_Func_Lookup_Table_t
{
	int (*pUserFunc)(String userArg);
	char userFuncKey[USER_FUNC_KEY_LENGTH];
	char userFuncArg[USER_FUNC_ARG_LENGTH];  <-- Remove this
	int userFuncRet;
	bool userFuncSchedule;
} User_Func_Lookup_Table[USER_FUNC_MAX_COUNT];

I am not sure why you need to store the userFuncArgs in the table. Once the function gets called at: 
int userFuncSchedule(const char *funcKey, const char *paramString)

There is no further need to store the arguments. It looks like in the  spark_protocol.cpp the function that handles the data:
bool SparkProtocol::handle_received_message(void) 
calls into the user function immediately by using the above labeled function.

**Comment by m-mcgowan** [comment]
Thanks very much for this @fearless40! I just implemented the changes in our private repo. (This will become public as soon as we sort out some 3rd party licenses.)
