### ISSUE TITLE
Printing empty String object should be a no-op

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#220]
See this community post:
https://community.spark.io/t/bug-in-string-and-a-few-minor-tweaks/4691/18?u=zachary

In particular, both of the following should do nothing. However, currently:

    Serial.print(String(NULL));

prints `0` and

    Serial.print(String(""));

crashes the Core.

**Comment by m-mcgowan** [comment]
Confimed that both are now a no-op - nothing is printed.

However, there was a compiler warning for `String(NULL)` .  In the cc3000 headers, `NULL` is incorrectly defined as 0 - an integer, this calls a different constructor than what might be expected:

`explicit String(int, unsigned char base=10);`

To invoke the C-string constructor, the type must be set to `const char*` either by explicit casting or by referencing a variable:

```cpp
const char* myString = NULL;
Serial.print(String(myString));
```
