### ISSUE TITLE
Increase UDP buffer size ?

### ISSUE THREAD

**Issue by natcl** [spark/firmware#224]
Would it be possible to increase the UDP read buffer size from 512 to a somewhat larger value (768 or 1024)
This would allow the Spark Core to read Artnet (dmx) packets.

Thanks.

**Comment by m-mcgowan** [comment]
I'm looking at the UDP class now, and thinking that the memory should be allocated dynamically. A new constructor argument will set the maximum packet send/receive size. 

```
UDP udp;  // default size of 512
UDP udp(1024);  // 1024 for read/write packets
```

How does that sound?

**Comment by natcl** [comment]
Yes that would be great !

**Comment by m-mcgowan** [comment]
Dynamic memory allocation has been added in the develop branch, will be part of the 0.4.5 release.
