### ISSUE TITLE
Add uint8_t override for UDPClient read?

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#231]
The TCPClient / UDPClient differ in that the UDPClient doesn't have a uint8_t read overload, so it's hard to reuse receive buffers in applications?

ref this thread:
https://community.spark.io/t/v0-2-3-firmware-ram-optimizations-shipped/5181/34?u=dave

Thanks,
David

**Comment by m-mcgowan** [comment]
`Print.write(const char*)` exists and we have the UDP.read(char*, int) overload to allow reading into a (signed) char buffer.
