### ISSUE TITLE
CONTRIBUTE link in Readme.md

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#235]
Seems like the link is left blank somehow. Where's the link to the instructions or NDA?

**Comment by m-mcgowan** [comment]
The current contribute link is broken - re-opening this so we can address it. Where should the contribute link point to?

**Comment by kennethlimcp** [comment]
I think is it supposed to point to: http://spark.github.io/

**Comment by m-mcgowan** [comment]
Fixed.
