### ISSUE TITLE
TCPClient slowdown

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#239]
When the cloud connection is 'active' by not including 'spark_disable_cloud', transfers over a TCPClient seem to slow down exponentially.

See this thread for reference and test code:
https://community.spark.io/t/tcpclient-slowing-to-a-crawl/5853/7

Theory: something in the cloud connection impacts other active sockets / and or causes reads to be missed that cause the TCP packets to 'backoff' as they are resent.

**Comment by m-mcgowan** [comment]
We're not able to fix this since the issues are inside the CC3000. It would be good to test this in the 0.4.5 release with the latest CC3000 service pack to see if the situation has improved. Volunteers most welcome.

**Comment by m-mcgowan** [comment]
Tested on Core with Service Pack 1.28 and 1.32 and both receive many 10's of K of data without any visible slowdown.  (Made a small change to the test case.)

Updating the CC3000 firmware is the fix here.
