### ISSUE TITLE
delay seems to be required during typical TCP / HTTP requests

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#244]
Is there some problem with our socket writes not blocking until everything is sent properly?  I seem to recall we had an issue with this in the past. 

another relevant thread:
https://community.spark.io/t/api-instapush-im-host-not-connecting-with-tcpclient-408-timeout/6002/6

**Comment by m-mcgowan** [comment]
There's not much we can do to fix this. There's nothing in our code that causes these issues other than bugs in the CC3000 firmware. Updating to 1.14 may fix this.
