### ISSUE TITLE
Serial2 Not Working in Web IDE

### ISSUE THREAD

**Issue by bkobkobko** [spark/firmware#245]
The code changes for the Serial2 feature are in the compile-server2 branch but the feature does not work in the web IDE right now since it also requires a makefile change.  The makefile is changed on the compile-server2 branch but I don't think the production makefile was updated.

**Comment by m-mcgowan** [comment]
Verified Serial2 library available in the webIDE by adding `#include "Serial2/Serial2.h"`.
