### ISSUE TITLE
"application.h" should be "Spark.h"

### ISSUE THREAD

**Issue by zsup** [spark/firmware#249]
Currently, projects need to `#include "application.h"` to get all of the Spark goodness. For the main .ino file, we do this automatically with our pre-processor. If anyone is building their own stuff, they add it themselves.

`#include "application.h"` is a confusing syntax, since you're not actually including an application; you're including the various dependent libraries.

In Arduino land, the equivalent is:

`#include "Arduino.h"`

This makes sense; you're basically saying "I'd like to include the Arduino libraries, please".

Our syntax should be similar, so I propose that we replace `#include "application.h"` with `#include "Spark.h"`, and we rename `application.h` to `Spark.h`. For the short term we should also keep `application.h` to maintain backward compatibility, and at some point announce that we are deprecating `application.h`, perhaps through a compiler warning, which should eventually become a verbose compiler error that says "You must change `application.h` to `Spark.h`".

Thoughts? @towynlin?

**Comment by plocher** [comment]
Sample "Arduino.h":
```
#include <application.h>

#define PI 3.1415926535897932384626433832795
#define HALF_PI 1.5707963267948966192313216916398
#define TWO_PI 6.283185307179586476925286766559
#define DEG_TO_RAD 0.017453292519943295769236907684886
#define RAD_TO_DEG 57.295779513082320876798154814105
#define EULER 2.718281828459045235360287471352

#define abs(x) ((x)>0?(x):-(x))
#define round(x)     ((x)>=0?(long)((x)+0.5):(long)((x)-0.5))
#define radians(deg) ((deg)*DEG_TO_RAD)
#define degrees(rad) ((rad)*RAD_TO_DEG)
#define sq(x) ((x)*(x))

#define lowByte(w) ((uint8_t) ((w) & 0xff))
#define highByte(w) ((uint8_t) ((w) >> 8))

#define bitRead(value, bit) (((value) >> (bit)) & 0x01)
#define bitSet(value, bit) ((value) |= (1UL << (bit)))
#define bitClear(value, bit) ((value) &= ~(1UL << (bit)))
#define bitWrite(value, bit, bitvalue) (bitvalue ? bitSet(value, bit) : bitClear(value, bit))
```

**Comment by bkobkobko** [comment]
I would just like to say that some of these `#defines` like abs(), round() and degrees()/radians() and previous min() and max() really hurt C++ libraries that have methods with those names.  In my opinion `#define`ing these is not a solution.

**Comment by plocher** [comment]
Agreed - but by including Arduino.h on the Arduino env, I get them #defined
for me.  Not templated or any other elegant way, so by definition (pun only
sort of intended...), the libs are already broken there.

For those of us trying to live in the Arduino world, it really doesn't
matter whether you have a better widget, if being better comes at the price
of incompatibility.  In my workflow, the wifi is a huge PLUS, the web
services is another huge PLUS, and the community interactions load up all
the bases (sorry, the Giants are playing tonight :-)  Unfortunately, all
those PLUS's are almost completely negated by how hard it is to leverage
the rest of the Arduino ecosystem.

This is a serious issue:  pretending to be a better Arduino with partial,
forked-but-out-of-date almost-compatible pieces is the absolute worst place
to be.

Almost none of the existing 'duino sketches and libs work out of the box
with the Photon.  The sad part is that many of them could - witness PaulS's
Teensy3, a Cortex M4 processor that is very well supported on the Arduino
IDE, or even the Zero and Due SAM/Cortex M0 boards.  Yes, pins and
processors still impact things, but hopefully gratuitous header file naming
and trivial behavior differences won't be one of the road blocks for long.

  -John

(think "Arduino++", not "Arduino--++")

**Comment by m-mcgowan** [comment]
We have a place for arduino defines that need to be added in "wiring/inc/spark_wiring_arduino.h". The "Particle.h" header has been added.
