### ISSUE TITLE
CC3000 should be initialized to allow non-US Wi-Fi channels by default

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#253]
International users are often running into issues when their access points are using channels 11 or above.  The CC3000 supports these upper channels, so we should turn them on by default:

Here's an example app that changes the scan settings:

```
void setup() {
   // WiFi.on();
    initWifi();
}

void loop() {

}

void initWifi() {
    unsigned long aiIntervalList[16];
    for (int i=0; i<16; i++) { aiIntervalList[i] = 2000; }
    wlan_ioctl_set_scan_params( 1000, 100, 100, 5, 0x1fff, -80, 0, 205, aiIntervalList );
    wlan_start(0);
}
```

**Comment by m-mcgowan** [comment]
Added code to the core's HAL to enable all channels. Tested channel 13 (the highest my router will go up to.) Working on both core and photon.
