### ISSUE TITLE
OTA stops working when Spark.publish() called at 2500ms intervals.

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#272]
Summary:

```cpp
void loop() {
    Spark.publish("logging", "abc");    
    delay(2500);
}
```
Causes OTA to stop working.

Sometimes the core will eventually freeze to magenta then reset. With smaller delays, the magenta is never visible and the cloud times out.

http://community.spark.io/t/unable-to-flash-code-to-the-spark-core-from-web-ide/6391/9

(@bkobkobko mentioned this might already have an issue, but neither he nor I could find it!)

**Comment by jenesaisdiq** [comment]
Hey guys, just found this problem again. It's really, really awful because it's simple, common, and completely breaks the development process. Plus, you could (effectively) brick a remote unit when adding code to inspect it.

Building on:
SPARK FIRMWARE V0.3.4  (OCT 21) CHANGELOG
core-firmware 6c98a17 
core-communication-lib d824a68 
core-common-lib 3cdaed3

**Comment by m-mcgowan** [comment]
We have 2 fixes for local development:
- upgrade to the 1.32 driver / 1.14 patch
- flash the latest bootloader, which includes factory restore - this doesn't reset wifi credentials, making reverting to known good firmware simpler.

**Comment by ScruffR** [comment]
I just stumbled over the same issue when helping this guy
http://community.particle.io/t/rapid-flashing-cyan-and-red-and-no-ability-to-reflash/12906

**Comment by towynlin** [comment]
Came up today in a support ticket. What fix can we recommend to novice users who do not build locally and do not use DFU or JTAG? It would be nice to recommend something other than "beware delay+publish, poll millis instead".

**Comment by CptanPanic** [comment]
Yes I too would like a solution that doesn't require building locally.  I am trying to understand why calling delay() is different than just checking millis() and letting loop fall through, since they both end up calling SPARK_WLAN_Loop()

**Comment by m-mcgowan** [comment]
I think we could fix `delay()` to call the background loop more often, particularly when we can see that there is still a large amount of time remaining in the requested delay period. The current situation is that delay is only called at most once per second - I think we can increase the throughput for how often delay is called to say 5 times a second - and if there is more than (say) 500ms remaining of the delay continue calling the background loop. This will ensure throughput without adversely affecting the application code.

**Comment by andyw-lala** [comment]
Has the worst-case/distribution of the background loop duration been
established ?

I agree that breaking delay() down into bite-sized pieces that allow all
normal cloud functions to continue is key; having this data will let you
drive the algorithm design with facts, not heuristics.

On Mon, Aug 10, 2015 at 8:51 AM, Matthew McGowan <notifications@github.com>
wrote:

> I think we could fix delay() to call the background loop more often,
> particularly when we can see that there is still a large amount of time
> remaining in the requested delay period. The current situation is that
> delay is only called at most once per second - I think we can increase the
> throughput for how often delay is called to say 5 times a second - and if
> there is more than (say) 500ms remaining of the delay continue calling the
> background loop. This will ensure throughput without adversely affecting
> the application code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/272#issuecomment-129460833>.
>



-- 
Andy

**Comment by dmiddlecamp** [comment]
:+1: to spending more time maintaining the cloud connection (once per second is way too low), but definitely agree with @andyw-lala

**Comment by m-mcgowan** [comment]
It's a good thought.  Since the background loop is network-bound, the figures obtained would vary (widely) depending upon network conditions. I feel that even with the facts we'd still end up simplifying it as a set of heuristics, since there would be no hard guarantees, just typical (by geographical region) and worst case.  

Now that we've improved the loop() throughput in 0.4.x to avoid continually blocking for 5ms on a socket receive, the execution time is less than 1ms in the best case.  The upper bound is unlimited since it depends upon network connectivity in the worst-scase scenario. For typical cases, it's about reading a TCP packet from the network and sending a response. It would be good to have figures for this, but again the times will vary by network.

I feel the most robust approach is to build it heuristically - measure the times of previous calls to the background loop and factor that into a decision about whether to run the background loop in `delay()`, taking into account the amount of remaining delay time and the expected execution time.

**Comment by andyw-lala** [comment]
Reading TCP shouldn't be subject to network effects. A packet is either
there or not.

Thinking of a reply or new packet and initiating it should also have a
bounded behaviour - whether it gets sent or not should be running off timer
ticks or some such, if processing is deferred.

The real fun and games comes when you need to close/re-open the connection
- that's a blocking call that might need DNS etc, but it seems to me like
we can characterize this and it will look like a bi- or tri- modal
distribution, and we should design for the most common cases.

It is universally accepted, except in hard-real-time systems, that
delay()-like substances delay for _at least_ the time specified, and
sometimes longer, depending on system load. We are not a hard-real-time
system, so we should document it that way.

I am glad to hear that the 5ms min delay has finally been neutered in
production code, that concept has been proven for a long while, the CC3000
does not barf up as long as you rate limit these requests externally; and
the BCOM has no such limitation.

On Mon, Aug 10, 2015 at 9:23 AM, Matthew McGowan <notifications@github.com>
wrote:

> It's a good thought. Since the background loop is network-bound, the
> figures obtained would vary (widely) depending upon network conditions. I
> feel that even with the facts we'd still end up simplifying it as a set of
> heuristics, since there would be no hard guarantees, just typical (by
> geographical region) and worst case.
>
> Now that we've improved the loop() throughput in 0.4.x to avoid
> continually blocking for 5ms on a socket receive, the execution time is
> less than 1ms in the best case. The upper bound is unlimited since it
> depends upon network connectivity in the worst-scase scenario. For typical
> cases, it's about reading a TCP packet from the network and sending a
> response. It would be good to have figures for this, but again the times
> will vary by network.
>
> I feel the most robust approach is to build it heuristically - measure the
> times of previous calls to the background loop and factor that into a
> decision about whether to run the background loop in delay(), taking into
> account the amount of remaining delay time and the expected execution time.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/spark/firmware/issues/272#issuecomment-129471670>.
>



-- 
Andy

**Comment by m-mcgowan** [comment]
With service pack 1.28, changing the delay to 250ms between calling the cloud didn't help. It seems as though publishing events every 2-4 seconds really does overload the CC3000.  Upgrading to 1.32 service pack and the problems disappear.

**Comment by m-mcgowan** [comment]
The fix for this is to roll out Service Pack 1.32. (Driver 1.14)

**Comment by dmiddlecamp** [comment]
weren't we / aren't we seeing this on the photon as well?

**Comment by m-mcgowan** [comment]
I don't believe so. I can double check to be sure.

**Comment by m-mcgowan** [comment]
Verified working on a photon with firmware v0.4.5-rc.1
