### ISSUE TITLE
Proposal: Tap MODE to toggle connection

### ISSUE THREAD

**Issue by zsup** [spark/firmware#276]
Currently, if you hold the MODE button for three seconds, it puts you into listening mode, and if you hold it for 10 seconds, it clears the Wi-Fi credentials.

Now that we've made it easy for people to control the connection to the Spark Cloud, it may be worthwhile to make a quick tap of the MODE button toggle the connection.

Pseudocode:

```cpp
when(BUTTON_TAPPED) {
  if (Spark.connected()) {
    Spark.disconnect();
  } else {
    Spark.connect();
  }
}
```

Thoughts? The downside would be that accidentally triggering the MODE button might be too easy.

**Comment by m-mcgowan** [comment]
As a stepping stone, I added system events for button pressed/released. The syntax isn't as elegant as some of those suggested here, but it gets the job done. We can wrap up in syntactic sugar later if needed.
