### ISSUE TITLE
Proposal: system events for system state changes

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#279]
At present, to detect changes in the core, user code has to continually poll. For example, to take action when the spark cloud disconnects or reconnects requires code like this:

```cpp
void loop() {
   static bool prev_connected = true;
   bool connected = Spark.connected();
   if (connected && !prev_connected) {
         // we know the cloud was now connected
   }
   else if (!connected && prev_connected) {
         // we know the cloud was now disconnected
   }
   prev_connected = connected;
}
```
This is code required for tracking one state change - multiply this a couple of times for tracking multiple items and I hope you see it quickly becomes unwieldy.

This would be simpler for the user if the core published system events that user code can listen to. These system events would cover:

- Wifi connected/disconnected, 
- Cloud connected/disconnected
- entering/exit listen mode
- entering sleep/waking up
- starting OTA flash, OTA flash complete
- cloud variable about to be read, read complete
- mode/setup button pressed/released
 - etc...

The user can register interest in system events by using a new proposed API:

```cpp
System.subscribe(tellMe);
```

Where `tellMe` is a user supplied function that receives notification of system events:

```cpp
void tellMe(SystemEventSource eventType, int data, void* pdata) {  
  switch (eventType) {
     case WIFI_ON:
     case WIFI_OFF:
     case WIFI_CONNECTED:
     case WIFI_DISCONNECTED:
     case SPARK_CONNECTED:
     case SPARK_DISCONNECTED:
     case SLEEP:
     case WAKEUP:
     case OTA_UPDATE_BEGIN:
     case OTA_UPDATE_IN_PROGRESS: // called after each chunk is received
     case OTA_UPDATE_COMPLETE:
     case LISTENING_BEGIN:
     case LISTENING_IN_PROGRESS:
     case LISTENING_COMPLETE:
           break;
  }
}
```

This allows user code to better interact with changes in the core. For example, the OTA_BEGIN notification allows user code to manage the state of peripherals before the potentially long OTA flash starts when user code is no longer run (e.g. [shutting off a sprinkler to avoid flooding a basement](https://community.spark.io/t/pre-ota-flash-function/4350/4?u=mdma).)

The system events callback signature allows the number of events to grow over time. The parameters `data` and `pdata` are presently unused, but will allow system events to evolve and provide more details in future. E.g. the `SPARK_DISCONNECT` event could indicate the disconnect reason - a call to Spark.disconnect() or environmental (no internet connection.)

This api avoids users having to write code to manage what is essentially a system responsibility, and allows a more fluid interaction between user code when key system changes take place.

**Comment by m-mcgowan** [comment]
Revisiting this. I want to try to balance memory use and simplicity, and compile-time safety (as C++ coders are used to.)

```
void wifi_handler()  {
   Serial.print("wifi_connected");
   Serial.print(WiFi.connected());
}

System.on(wifi_connected + wifi_disconnected, wifi_handler);

// equivalently
System.on(wifi_connection_changed, wifi_handler);

```

The function that is passed can have this form in addition to the no-argument function:
```
void handler(event_type, event_value, params);
```

This will allow callers to fine-tune their handlers to specific events as well as allow a handler for many types of event, which is useful for implementing loggers, or handling many events in the same way:

```
System.on(all_events, log_event);

System.on(wifi_event, handle_wifi);  
// same as 
System.on(wifi_listening_started+wifi_listening_stopped+wifi_connected+wifi_disconnected ..etc.)

System.on(cloud_event, handle_cloud);
// same as
System.on(cloud_connected+cloud_disconnected+cloud_connecting+cloud_ota_update_start+cloud_ota_update_end)
```

The events will be encoded into a bitvector as a 64-bit value. This allows sets of events to be represented compactly.

**Comment by kneuron** [comment]
Are these what are referred to in the [latest system firmware release](https://github.com/spark/firmware/releases/tag/0.4.3-rc2)? Is there a list of system events and a description of how to use them anywhere? Most interested in setting a timeout for listening mode, and this seems like it might be the right way to do it.

**Comment by m-mcgowan** [comment]
Please see https://community.particle.io/t/photon-listening-mode/12870/31?u=mdma

**Comment by kneuron** [comment]
Thanks for the super quick response! Looking forward to trying it out.

**Comment by m-mcgowan** [comment]
System events were introduced in 0.4.3. The infrastructure is in place and has been tested, so closing this issue.  Documentation will follow this sprint.
