### ISSUE TITLE
TCPClient print causes slow speeds (write works)

### ISSUE THREAD

**Issue by cloudformdesign** [spark/firmware#281]
referenced by me in this thread 

http://community.spark.io/t/max-speed-of-tcp-data-and-proper-coding-methods/6638/8

Here is the code I used to make it transfer fast (would be worthwhile to add to examples)

https://gist.github.com/cloudformdesign/72f8af081453c0e47e88

**Comment by m-mcgowan** [comment]
Closing this as it's fixed and released.
