### ISSUE TITLE
Sleep isnt sleep, it is timed restart

### ISSUE THREAD

**Issue by jacobrosenthal** [spark/firmware#283]
Sleep as implemented isnt very traditional. Its more of a timed watchdog restart. It doesnt maintain state and worst of all reset all pin states.

Is this by design, Is there interest in a traditional sleep implementation?

**Comment by mtnscott** [comment]
@satishgn Do you know if this is planned for the Photon release?

**Comment by satishgn** [comment]
Yes this is implemented on Photon. so should be available by default.
