### ISSUE TITLE
Bit Fields not compressing data

### ISSUE THREAD

**Issue by cloudformdesign** [spark/firmware#285]
Hey, I'm playing with bitfields on the spark

```
#include "allduino.h"

// testing structure lengths
//


struct OddData{
    unsigned int mybool         :1;
    unsigned int shortbyte      :7;
} odd_data;


struct Data12{
    unsigned int data1          :12;
    unsigned int data2          :12;
    unsigned int data3          :12;
    unsigned int data4          :12;
} data12;


struct Data12 data12_array[10];


void setup(){
    Serial.begin(115200);
    odd_data.mybool = false;
    odd_data.shortbyte = 0;
}

void print_struct(){
    RUN_ONLY_EVERY(500);
    Serial.print("bool:"); Serial.println(odd_data.mybool);
    odd_data.mybool ++;
    odd_data.shortbyte = 128;
    Serial.print("shortbyte = 128:"); Serial.println(odd_data.shortbyte);
    Serial.print("size odd_data:"); Serial.println(sizeof(odd_data));
    Serial.print("size data12:"); Serial.println(sizeof(data12));
    Serial.print("size data12_array:"); Serial.println(sizeof(data12_array));
}

void loop(){
    HEARTBEAT();
    print_struct();

}
```

This prints out the following:

```
shortbyte = 128:0
size odd_data:4
size data12:8
size data12_array:80
bool:1
shortbyte = 128:0
size odd_data:4
size data12:8
size data12_array:80
bool:0
```
Over and over again

Issues:
- bit packing works as far as getting the right data! shortbyte should == 0 and bool should alternate back and forth
- The size of data12 == 8 bytes, it should be 6 bytes (that is the point of bit packing). It seems to be just taking a whole new byte for each value.
- The size of odd_data == 4 bytes when it should clearly be 1 byte. This one is even weirder, I have no idea what it is doing.

**Comment by m-mcgowan** [comment]
We can't fix this since it's a feature of C99, but the clarification above will help work around the issue.

**Comment by cloudformdesign** [comment]
yes, thankyou. Sorry I forgot this was still open.

**Comment by m-mcgowan** [comment]
No probs! Just doing a spot of spring cleaning! I hope you got your issue resolved!
