### ISSUE TITLE
Both delay(); and Delay(); are user-visible leading to problems

### ISSUE THREAD

**Issue by bkobkobko** [spark/firmware#291]
See this thread in the forum for a user who type `Delay(1000);` when they meant `delay(1000);` which made for a hard to diagnose bug!  The internal function `Delay()` should not be so easy to reach and needs a name change.

https://community.spark.io/t/unable-to-publish-without-consistent-delay/6791

Delay (capital-D) is in hw_config.c
It is called in spark_wlan.cpp and wifi_credentials_reader.cpp

**Comment by m-mcgowan** [comment]
The Delay() function has been removed with the 0.4.0 refactor. 
Also, with the HAL layer, the hardware files (where `Delay` was declared) can be excluded by default. This will keep the default namespace free from these obscure function.
