### ISSUE TITLE
TCPClient read() data missed

### ISSUE THREAD

**Issue by dilbert168** [spark/firmware#339]
After receiving 8030 bytes, the CC3000 will start missing data.
Wonder how this workaround can be included ?

Refer to below for details.
http://community.spark.io/t/tcpclient-read-data-missed/6904/10
http://e2e.ti.com/support/wireless_connectivity/f/851/t/365625.aspx

**Comment by m-mcgowan** [comment]
This was a problem with the code timing out (the maximum delay was 2000 ms) which was being overstepped due to TCP exponential backoff. AFAIK, if data is received, it's always in order and complete.  Happy to re-open if that's not the case.

**Comment by dilbert168** [comment]
I am still confused with the answer to the problem discovered.  The "code
timing out" referring to which code ?  What is the possible solution to fix
this ?

**Comment by m-mcgowan** [comment]
What I mean is that it looks like the bug was in your code since it wasn't expecting a delay of more than 2000ms, but this delay did happen in connecting with exponential backoff  when reading TCP packets.

**Comment by dilbert168** [comment]
I do not think it is a bug in my code as I can receive data normally up to certain size of a file.
The test code I put in not doing anything except counting the received data to ensure firmware not over run.  Also, below comments had exact same finding as mine.  
May be the bug is inside the CC3000 driver from TI.

http://e2e.ti.com/support/wireless_connectivity/f/851/t/365625.aspx
