### ISSUE TITLE
MODE button not working in Semi or Manual Mode

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#343]
Using `SYSTEM_MODE(SEMI_AUTOMATIC)` or `SYSTEM_MODE(MANUAL)`, the core does not respond to the MODE button and does not perform either Listening Mode or Factory reset.

Example code:
```

SYSTEM_MODE(MANUAL);

void setup(){
    pinMode(D7,OUTPUT);
    digitalWrite(D7,LOW);
}

void loop(){
        digitalWrite(D7,!digitalRead(D7));
    }
```

Initial findings show what `WiFi.on()` must be called once for the core to pick up MODE button status

Mostly likely, the culprit is the flag `SPARK_WLAN_SLEEP` set 1 for **MANUAL** and **SEMI_AUTOMATIC** upon boot up

https://github.com/spark/firmware/blob/7d5d7d1f74d8d8be410f08102a0944e3a2824cf4/src/spark_utilities.cpp#L116

**Comment by m-mcgowan** [comment]
With MODE button being enabled now when `SPARK_WLAN_SLEEP` is true, I think we can close this issue?

**Comment by m-mcgowan** [comment]
Issue fixed.
