### ISSUE TITLE
Spark identify mac address

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#352]
It will be great for more information to be available with the 'i' command in Listening mode to aid new users.

Mac address --> some setup requires this for whitelisting and the current approach is to flash a custom firmware and perform a prinout (need spark-cli, dfu-util, serial terminal)

**Comment by kennethlimcp** [comment]
Found this function here: https://github.com/spark/firmware/blob/feature/hal/platform/NET/CC3000/CC3000_Host_Driver/nvmem.c#L197

but doesn't seem to be exposed via some user function as of now. I can help to get this feature running if someone suggests under where (hal or wlan etc) should this reside.

**Comment by m-mcgowan** [comment]
Hi kenneth! Thanks for the offer to help, it would have been great to have shown you were to put the code so you can do it, but I'd already done it when I saw your message.  The changes are in this commit: https://github.com/spark/firmware/commit/d7079dfc608de89d134316db01fbbd9aa1b81e47

**Comment by m-mcgowan** [comment]
I chose to make it a new command instead of adding to the existing 'i' command since the spark cli parses the 'i' command output, so I didn't want to mess with that.

**Comment by kennethlimcp** [comment]
Fixed by this commit : https://github.com/spark/firmware/commit/d7079dfc608de89d134316db01fbbd9aa1b81e47#diff-6217688b0e210a067a90d2cc775ae4a3 so i'm gonna close this.

**Comment by jonbgallant** [comment]
I would like to be able to get the MAC address via CLI before connecting it to WiFi.  Should I be able to just open box, plug in USB cable, put in listening mode and call "particle setup m" to get it?

**Comment by kennethlimcp** [comment]
You will need to use a Serial terminal for now since it's not supported by the CLI (yet)

**Comment by jonbgallant** [comment]
I plugged a new Photon in to USB, connected via Putty and hit "i" and got the Id, then I hit "m" and it says "Your core MAC address is: " without rendering the MAC Address and it hangs Putty.  Does that mean I need to connect it to WiFi first?  I was hoping to not do that because I want to get MAC address of Photons in bulk for a corporate network whitelist and don't want to have to connect each core to WiFi first.

I'm updating the firmware now, just in case it didn't have the latest when shipped to me.  I should be able to get the MAC without connecting to WiFi first right?

**Comment by jonbgallant** [comment]
I tried to update the firmware, but it looks like WiFi is required to do that.  Once, again, just for clarity, I would like to get the MAC address before connecting WiFi.

**Comment by dmiddlecamp** [comment]
hmm, I plugged a photon that had never been online and hit 'm', and got the mac address successfully.  Maybe these are photons with the very old serial bug firmware?

**Comment by jonbgallant** [comment]
That might be the case, these are the kickstarter photons. Is there a serial command to get the firmware version number?

**Comment by m-mcgowan** [comment]
Hi @jonbgallant! You don't need wifi to update the system firmware if you have particle-cli installed - you can download the files and flash using USB. Please see the instructions at https://github.com/spark/firmware/releases/tag/0.4.3-rc2.

**Comment by jonbgallant** [comment]
Thanks. Is there a serial command to get the current firmware version?

**Comment by m-mcgowan** [comment]
You can type 's'. If it's manufacturing firmware, it will say 'modular:no'. I'm guessing you'll see that since the device has never been connected, so no updates have been applied.

**Comment by jonbgallant** [comment]
OK, Yeah, it says modular:no.  So it looks like I won’t be able to get the MAC address without of the box Photon.

**Comment by jonbgallant** [comment]
I’m trying to get the dfu-util to run, but I’m getting this error:

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
No DFU capable USB device available


The Photon is flashing yellow.
I see the Photon in Device Manager and it says it is in DFU mode.

**Comment by jonbgallant** [comment]
I figured it out and blogged step-by-step instructions here: http://blog.jongallant.com/2015/08/particle-photon-firmware-flash-windows.html


From: Jon Gallant
Sent: Tuesday, August 11, 2015 11:29 AM
To: 'spark/firmware' <reply@reply.github.com>
Subject: RE: [firmware] Spark identify mac address (#352)

I’m trying to get the dfu-util to run, but I’m getting this error:

Invalid DFU suffix signature
A valid DFU suffix will be required in a future dfu-util release!!!
No DFU capable USB device available


The Photon is flashing yellow.
I see the Photon in Device Manager and it says it is in DFU mode.

**Comment by jonbgallant** [comment]
I created another post on how to get your MAC Address before connecting to WiFi http://blog.jongallant.com/2015/08/particle-photon-mac-address.html

**Comment by technobly** [comment]
Very nice @jonbgallant, thanks!
