### ISSUE TITLE
Why are there headers on Spark/communication/src?

### ISSUE THREAD

**Issue by rei-vilo** [spark/firmware#356]
Why are there headers on `Spark/communication/src`?

* coap.h 
* events.h 
* functions.h 
* handshake.h 
* spark_descriptor.h 
* spark_protocol.h

All other headers are in a specific `inc` folder.

**Comment by m-mcgowan** [comment]
This has been addressed in the private photon repo - will release as soon as we have obtained a needed 3rd party license.

**Comment by rei-vilo** [comment]
Great!
