### ISSUE TITLE
design flaw in TCPServer/TCPClient

### ISSUE THREAD

**Issue by gorsat** [spark/firmware#358]
TCPServer::available is returning a copy of its own private member _client which in turn contains a copy of the TCPServer's _sock. When you call TCPClient::stop on a client instance (copy) you've gotten from TCPServer::available, the socket is closed in TCPClient, but the TCPServer's _sock variable does not reflect this. This means that the next time you call TCPServer::available, the code assumes it has a valid, open, listening socket and it just calls accept() on it. But the socket was closed, so that call will fail, hence available will return TCPClient::(MAX_SOCK_NUM) and it will fail to set its own private copy of the socket (_sock) to MAX_SOCK_NUM which means TCPServer::available will silently fail from then on. 

A few suggestions:

1) TCPServer should not return a copy of its private client instance. I don't even think it should have its own copy of TCPClient. (see #3)
2) As soon as TCPServer has handed off a new client connection (e.g. via ::available) it should forget about the socket it used for that client. If the server is going to listen again then it needs to do so with a new socket. A socket that the server has already handed off has nothing to do with future connections -- zero, nada, nil. So holding onto that socket is pointless and just causes trouble.
3) TCPServer should not inherit from Print or Stream. This just confuses the developers and the code they write. Just look at your own examples or the code that folks have posted in the forums. They don't know whether they're supposed to send data using TCPServer::print or TCPClient::print. The server's entire job is to listen for connections and create TCPClient instances. If you really, really want to provide the extra functionality of being able to send messages to all clients simultaneously (as the documentation seems to imply) then you're going to have to do some major surgery on the code anyway. I suggest you just simplify rather than taking that complicated path.

**Comment by piettetech** [comment]
Is this thread dead?  I still can't use TCPServer reliably.  I was wondering if anyone has any ideas?  I wanted to check before I start writing my own implementation of TCPServer.

**Comment by towynlin** [comment]
Thanks for following up @piettetech. If we can clearly articulate a specific problem, with a [short, self-contained, correct example](http://sscce.org/), and if we can clearly describe the observed vs. desired behavior in that case, we'd be happy to work on it.

So far in this thread we haven't managed to get there yet. As @gorsat said, too, all Spark efforts are pouring into the Photon right now, not the Core. We have an aggressive timeline, and the challenges have us, as a composer friend of mine says, "thrilled and daunted."

If you are inclined to write your own implementation of TCPServer, I would love to see how that goes!

**Comment by m-mcgowan** [comment]
From the opening discussion:
> TCPServer::available is returning a copy of its own private member _client which in turn contains a copy of the TCPServer's _sock.

AFAICT this isn't the case.  The server doesn't pass out it's `_sock` member, which is the server-side socket handle. It does pass out `sock` (no leading underscore) - a local variable that the most recently accepted client socket.

I'll close this issue since I don't see any evidence of the statement problem. Happy to re-open if someone can provide a SSCCE to exemplify the problem.

**Comment by gorsat** [comment]
You're right. That was just bad code reading on my part. Still, the weird socket behavior continues for many users. But I'm sure it's discussed on other threads and, hopefully, won't be a problem on Photon.
