### ISSUE TITLE
Wifi.localIP() in SEMIAUTOMATIC mode. 

### ISSUE THREAD

**Issue by tjtrolinger** [spark/firmware#361]
Wifi.localIP() returns 0.0.0.0 in SEMIAUTOMATIC mode when connected to Wifi but not connected to Spark cloud

**Comment by piettetech** [comment]
@tjtrolinger It takes a bit of time for `WiFi.localIP()` to get the proper value.  If you test immediately after you turn on the WiFi (and after waiting for it to connect) it will return 0.0.0.0  If you add a slight delay it will return the proper IP address.  I have noticed this behavior in all modes.

When you use the Spark Cloud this delay is already embedded in the code that connects to the cloud so it will always return the proper value after establishing the cloud connection.

**Comment by m-mcgowan** [comment]
@tjtrolinger - did the advice @piettetech offered help you resolve this issue?

**Comment by m-mcgowan** [comment]
The IP data is fetched as part of background processing - adding a call to `SPARK_WLAN_Loop()` after WiFi is connected will populate the IP details.
