### ISSUE TITLE
Spark events not working

### ISSUE THREAD

**Issue by robertdolca** [spark/firmware#365]
With the exactly the same code the 2nd core was receiving events but this change around 11th of December. Now it receives only one event and then it doesn't any more. Both cores are online and working and the events are being sent (checked with Spark CLI).

**Comment by kennethlimcp** [comment]
@robertdolca , if you have some code i'll be happy to test it out.

**Comment by robertdolca** [comment]
The code is here https://gist.github.com/robertdolca/c5240e6d5ee18ce3c3c8
Harrison replied to my support ticket but no luck yet.

**Comment by kennethlimcp** [comment]
@robertdolca , is there a code for the other core then?

**Comment by robertdolca** [comment]
https://gist.github.com/robertdolca/84c78855f6bface51491
https://github.com/pkourany/idDHT22Spark

**Comment by kennethlimcp** [comment]
Seems positive on my side with consistent triggering of the subscribe event handler. Have replied in your gist so do test and see how it goes ;)

**Comment by robertdolca** [comment]
The events events are being published. The issues is that they are not being received.

**Comment by kennethlimcp** [comment]
Please take a look at my comments in your gist. i used the same test code for yours with a simplified test code to publish once every 3 seconds and can see that the eventhandler is being triggered.

**Comment by robertdolca** [comment]
I understand now. I will test it when I get home. So you are saying that the delay is causing the issue?

**Comment by robertdolca** [comment]
I've checked and the event is not fired at all. I've updated the code on gist.

**Comment by kennethlimcp** [comment]
@robertdolca, let's move the conversation here instead: https://community.spark.io/t/spark-events-handler-not-triggering/9173

**Comment by m-mcgowan** [comment]
@kennethlimcp  - is there anything we need to look into here, or can we close this?

**Comment by kennethlimcp** [comment]
Ok to close. :)

**Comment by m-mcgowan** [comment]
:+1: cheers!
