### ISSUE TITLE
Photon long handshake => malformed description message

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#370]
On prototype photon boards, the cloud handshake often takes many seconds longer than expected. After some digging into this, we found that the device service is receiving a malformed CoAP description message. Here are two examples in xxd format:

```
0000000: d5ff 267d 9521 7b22 6622 3a5b 5d2c 2276  ..&}.!{"f":[],"v
0000010: 223a 7b7d 7d                             ":{}}
```

```
0000000: 2159 bc92 3fe9 7b22 6622 3a5b 5d2c 2276  !Y..?.{"f":[],"v
0000010: 223a 7b7d 7d                             ":{}}
```

In both cases the first 6 bytes are malformed, whereas everything after that is fine. In particular, the device service is crying foul when the most significant 2 bits of the first byte of the message (the CoAP version) are anything other than `01`, the only value allowed by the CoAP spec.

As can be seen obviously in [the code](https://github.com/spark/firmware/blob/feature/hal/communication/src/spark_protocol.cpp#L612-L617), the first 2 bytes should always be `0x61 0x45` and the sixth byte should always be `0xff`. The 3rd, 4th, and 5th bytes may be anything.

I suspect one of two things is happening. Either:

- the RTOS on the Photon is interleaving access to `queue` so that those bytes are being overwritten (e.g., by a `blocking_receive`) before we finish the `blocking_send` of the description message, or
- whatever resides immediately before `queue` in memory is writing beyond the end with pointer math and the buffer overrun is not being caught by the compiler

Low priority for the moment (since handshake always eventually succeeds), but @m-mcgowan take a look when you're in the mood for some low level debugging.

**Comment by m-mcgowan** [comment]
Fixed. It was a problem in the socket layer.
