### ISSUE TITLE
WiFi.RSSI() should not panic core [CLOSED]

### ISSUE THREAD

**Issue by piettetech** [spark/firmware#377]
The function WiFi.RSSI() will cause the core to panic if the WiFi is disabled.  The function should just return a '0' value to indicate the WiFi is disabled.  

Normal operation is to return a value between [-1 and -127] to represent the signal strength in dB.  Error conditions are represented by a return values of [+1] for CC3000 issue and [+2] for a timeout in the function.  I suggest returning a value of [0] when the WiFi is not enabled.

**Comment by zsup** [comment]
:+1:

**Comment by m-mcgowan** [comment]
Fixed! (for photon and core).

**Comment by piettetech** [comment]
Awesome!
