### ISSUE TITLE
WifiCredentialsReader creates a new serial connection

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#384]
When the user firmware has already created a serial connection, and the user then starts listening mode, the previous serial connection is dropped.

It would be smoother if the wifi credentials reader created a serial connection only when one doesn't exist.

`USBSerial` class could have an additional method baud() that returns the current baud rate, or 0 if not connected. Wifi credentials reader checks value and only calls `Serial.begin()` when the baud rate is returned as 0.

**Comment by piettetech** [comment]
+1

**Comment by m-mcgowan** [comment]
fixed in feature/hal branch
