### ISSUE TITLE
USB Serial.peek() should return first available char

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#387]
Currently, according to this community thread:
http://community.spark.io/t/serial-peek-always-returns-255/9640

Serial1 & Serial2 correctly implement the `peek()` method, but USB Serial does not, only returning -1.

Our documentation:
http://docs.spark.io/firmware/#serial-peek

**Comment by pkourany** [comment]
The fix looks good.  When can it be pushed?

**Comment by towynlin** [comment]
Not sure — a matter of weeks. We already have firmware deployment process discussions on the calendar. Certainly no later than when the Photon ships; with luck sooner.

**Comment by m-mcgowan** [comment]
Closing this since it's fixed in the feature/hal branch.
