### ISSUE TITLE
System.FactoryReset() function

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#393]
We have the soft rest exposed using `System.Reset()` but some users are looking for a complete Factory Reset via code.

See: 

https://community.spark.io/t/hard-factory-reset-in-software/9919

**Comment by m-mcgowan** [comment]
There is

```
    System.factoryReset();
    System.bootloader();
```

In the wiring API but these are not documented. (I don't know why not.)

`factoryReset()` reboots the device and instructs the bootloader to perform a factory reset.

`bootloader()` reboots the device and enters DFU mode.

**Comment by kennethlimcp** [comment]
Can we get them tested and baked into HAL for documentation merged with the photon release?

**Comment by m-mcgowan** [comment]
They've been around for a long time. Already tested and working!
