### ISSUE TITLE
ability to retrieve configured AP details

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#397]
On the photon, the configured AP details are stored in the DCT area, so we could potentially make these available via an API. 

Is that useful?

**Comment by piettetech** [comment]
was there another proposition for gaining access to the AP details?

**Comment by piettetech** [comment]
+1 Yes, it would be good to get the AP details.

**Comment by m-mcgowan** [comment]
What do you think is a typical use case @piettetech for this?

**Comment by m-mcgowan** [comment]
Closing.  If someone wants this, please describe a good user story for this feature (rationale) then we can re-open and consider implementing.
