### ISSUE TITLE
UDP.write should buffer and nothing should be sent until UDP.endPacket

### ISSUE THREAD

**Issue by jnm2** [spark/firmware#407]
`UDP.write` and `UDP.endPacket` are broken. According to the Spark docs, and common sense, `UDP.write` provides a buffer for you so that you don't have to do your own buffering. Then when you call `UDP.endPacket`, everything you have written gets sent as a single packet.

Instead, `UDP.write` sends a packet every time it is called. `UDP.endPacket` does not function.

Since UDP inherits from Stream, this is especially problematic. Some of the write methods call `UDP.write` many times in the process of writing a single piece of data, but then `UDP.write` fires each tiny piece off in its own individual packet. This will give newbies a skewed idea of UDP and will frustrate people who know what they are doing. Please fix this.

**Comment by bkobkobko** [comment]
As I said in the forum, this is an acknowledge by TI fact of life with TI CC3000 on the Spark Core.  Photon will be better.

**Comment by jnm2** [comment]
What would it take to fix the UDP class?

**Comment by jnm2** [comment]
I would submit a pull request with the fix but I feel somewhat shy. Would that be welcome? I would have a couple questions.

**Comment by m-mcgowan** [comment]
Pros are always welcome!

**Comment by jnm2** [comment]
Okay! Questions:

 * Should the buffer be statically or dynamically allocated? It'll have to support the MTU size, but it could also be optionally given a lower max in the constructor. For example, my app never sends more than 69 bytes per packet.
 * Is there some kind of error-reporting precedent to be consistent with the rest of the firmware? What should happen when you `write` without first calling `beginPacket`, or try to write too much?

**Comment by jnm2** [comment]
Hey I'm new, is there a process to follow? I have those questions before I can help out here.

**Comment by m-mcgowan** [comment]
Hi @jnm2! Apologies for the delay - here's some answers for you! :-)

- I suggest having a constructor that takes `uint8_t* buffer, size_t buffer_size` so that the caller can decide how best to allocate the buffer and how large to make it.
- for error handling, use return codes to indicate errors. E.g. having write return 0 when it can't write any more data because the buffer is full. While it's of course good practice to detect caller problems such as a write() before beginPacket() it has to be balanced with cost of detecting those problems.

It would be great if you could provide details of how you test this (e.g. source code for any UDP servers you make), since we also want to test the same on the Photon.

As to process - please see http://spark.github.io/#Contributions

I hope that's enough to get you started, but of course please ask questions as the need arises!

**Comment by jnm2** [comment]
Thanks @m-mcgowan. I'm testing against ASP.NET's [UdpClient](https://msdn.microsoft.com/en-us/library/system.net.sockets.udpclient.aspx) on the server side, so I'm not sure what you'd want as far as testing.

**Comment by m-mcgowan** [comment]
Testing that sending and receiving respects packet boundaries would be a great start. 

Looking at the [arduino sources](https://code.google.com/p/arduino/source/browse/trunk/libraries/Ethernet/Udp.h?r=1094), there is the `sendPacket()` function that sends an entire packet in one operation without needing `beginPacket()`/`endPacket()`  I would imagine that would avoid confusion and avoids unnecessary buffering when the caller allocates their own buffer, e.g.

```cpp
UDP udp;
char buf[512];

void sendSomething()
{
    // fill the buffer `buf`  
    buf[0] = 0; // etc..
   udp.sendPacket(buf, 512, address, port);
}
```

**Comment by bkobkobko** [comment]
In my experience and reading, I do not believe that the TI CC3000 can distinguish received UDP packet boundaries.

I also think in whatever changes are made in this area, Arduino compatibility should be a very high priority.

**Comment by loopj** [comment]
Looks like this is finally being fixed in #452 !

**Comment by jnm2** [comment]
I see you are taking the dynamic allocation route after all. Good stuff!
I'm still waiting for the Photons we ordered so I can resolve the problem with the packet boundaries, but it looks like everything is taken care of.

**Comment by m-mcgowan** [comment]
The fix has been merged into develop for anyone that's available to test.

**Comment by m-mcgowan** [comment]
Tested working on the NTP client in `user/tests/wiring/networking`
