### ISSUE TITLE
UDP.parsePacket and UDP.read do not keep packets separate

### ISSUE THREAD

**Issue by jnm2** [spark/firmware#408]
`UDP.parsePacket` and `UDP.read` are broken. The Spark will sometimes receive incoming packets `AAA`, `BBBBB` as `AAABBBBB`. I need to be able to rely on the return from `parsePacket` to tell be the length of the next unread packet.

It's an embarrassment for a serious library to get the basic UDP fundamentals wrong. This will give newbies a skewed idea of UDP and will frustrate people who know what they are doing. Please fix this.

**Comment by bkobkobko** [comment]
This an acknowledged fact of life on the TI CC3000 and there is no work-around.

Photon will be better.

**Comment by jnm2** [comment]
Yes, thank you. I found that thread when my posts were moved.
