### ISSUE TITLE
Update firmware README.md

### ISSUE THREAD

**Issue by nanofortran** [spark/firmware#418]
On the mac side of things, gcc-arm-none-eabi no longer compiles firmware correctly; however, gcc-arm-none-eabi-48 works. This is cited at the bottom of this gist:
https://gist.github.com/joegoggins/7763637

Please change the README.md to reflect that . . .

```
brew install gcc-arm-none-eabi
```
should be changed to
```
brew install gcc-arm-none-eabi-48
```

It worked for me!
jg

**Comment by m-mcgowan** [comment]
This is done. Thanks for the prompt!
