### ISSUE TITLE
Photon RTOS

### ISSUE THREAD

**Issue by mojtabacazi** [spark/firmware#445]
Is there any documentation for the RTOS used in Photon? I noticed it's a part of WICED SDK but not sure how to download that. 

Is it possible to use Photon RTOS without loading  wiring stuff?

**Comment by m-mcgowan** [comment]
I think I can answer your question better if I know what you are trying to achieve.

**Comment by mojtabacazi** [comment]
To be honest, I'm confused about how this whole thing works. Can you point me to a document explaining WICED ? And also Photon Firmware?

Thank you
