### ISSUE TITLE
Core compile is showing undefined reference to `socket_create_tcp_server'

### ISSUE THREAD

**Issue by thomast74** [spark/firmware#459]
/tmp/cca62r7B.ltrans21.ltrans.o: In function `TCPServer::begin()':
/home/thomast74/Projects/spark-firmware/main/src/spark_wiring_tcpserver.cpp:44: undefined reference to `socket_create_tcp_server'

Looking at the source code for /hal/src/core/socket_hal.c the method socket_create_tcp_server is not implemented but socket_hal.h requires it. 
The socket_hal.c file includes a socket_create_nonblocking_server but this method has a different signature.

**Comment by m-mcgowan** [comment]
Fixed in the commit above. @thomast74 I'd be grateful if you could please confirm the fix so I can close this issue.

**Comment by thomast74** [comment]
Compile works and application with these changes works as well. I think problem is resolved.

Thanks

**Comment by m-mcgowan** [comment]
Thanks for getting back.
