### ISSUE TITLE
CLOCK_SPEED_100KHZ + CLOCK_SPEED_400KHZ not defined

### ISSUE THREAD

**Issue by pomplesiegel** [spark/firmware#463]
Particle Dev cannot resolve the symbols CLOCK_SPEED_100KHZ and CLOCK_SPEED_400KHZ

**Comment by technobly** [comment]
### Verified with app in Particle Build:
```cpp
// #include "i2c_hal.h"

void setup() {
    Wire.setSpeed(CLOCK_SPEED_100KHZ);
    Wire.setSpeed(CLOCK_SPEED_400KHZ);
    Wire.begin();
}

void loop() {

}
```

If you include i2c_hal.h it will compile though.  Not ideal so we'll resolve this!  Thanks for reporting this @pomplesiegel
