### ISSUE TITLE
0.4.3 release for Photon/P1 wrong location for P1 2b04:d006 should be 2b04:d008

### ISSUE THREAD

**Issue by wesner0019** [spark/firmware#485]
P1:

dfu-util -d 2b04:d006 -a 0 -s 0x8020000 -D system-part1-0.4.3-p1.bin
dfu-util -d 2b04:d006 -a 0 -s 0x8060000:leave -D system-part2-0.4.3-p1.bin
 
These should be:
dfu-util -d 2b04:d008 -a 0 -s 0x8020000 -D system-part1-0.4.3-p1.bin
dfu-util -d 2b04:d008 -a 0 -s 0x8060000:leave -D system-part2-0.4.3-p1.bin

**Comment by m-mcgowan** [comment]
Thanks. fixed! (Copy paste error!)

**Comment by wesner0019** [comment]
just saw this too;
this location also needs updating
so devices can be returned to factory condition. To apply, download the file then run dfu-util -d 2b04:d006 -a 0 -s 0x8020000:leave -D unlocker-p1.bin

**Comment by m-mcgowan** [comment]
You don't need to use unlocker when flashing via DFU.

**Comment by m-mcgowan** [comment]
I see what you mean - the DFU ID was d006. Fixed. Thanks :-)
