### ISSUE TITLE
PHOTON: PWM outputs 500Hz on RX/TX pins and 625Hz on D0-D4/A4/A5/WKP pins

### ISSUE THREAD

**Issue by technobly** [spark/firmware#492]
Found that PWM outputs 500Hz on RX/TX pins and 625Hz on D0-D4/A4/A5/WKP pins. Should be 500Hz for all pins. Tested on Photon.

// The Photon should have 9 PWM pins: D0, D1, D2, D3, A4, A5, A7, RX and TX.
//
// EXAMPLE USAGE
// Outputs PWM on pwmPin
int pwmPin = D0;

void setup() {
  pinMode(pwmPin, OUTPUT);
  analogWrite(pwmPin, 64); // 25% PWM at 500Hz
}

**Comment by satishgn** [comment]
Investigating #492

**Comment by satishgn** [comment]
All PWM channels on Photon should now output 500Hz.

**Comment by satishgn** [comment]
Fixed in branch: feature/photon-pwm-and-tone-fix (should later be merged with develop/latest before release)

**Comment by m-mcgowan** [comment]
Just checked, this has been merged into develop. I deleted the branch now. (It's a good idea to create a PR from the branch - it's makes it easier to track when the changes have been merged.)
