### ISSUE TITLE
Wiring API supports multiple Network types

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#502]
At present the Wiring API supports only WiFi, with calls such as `WiFi.on()` / `WiFi.off() / WiFi.setCredentials()`. 

The Photon will have an `AP` mode network, the Electron will support cellular and surely there will be other devices with further types of network.

At outlined [here](https://github.com/spark/firmware/issues/251#issuecomment-51329282), a simple, yet extensible way to provide this to the application developer is to introduce a common `Network` base class for all networks, so when the application developer wants to work with the primary network, but doesn't care what type of network it is (WiFi, Cellular, Ethernet) they can write

```
Network.on();
Nework.off();
Network.connect();
Network.disconnect();
```
etc..

On a specific platform they can also reference the network type directly, so 

```
WiFi.on()
WiFi.off();
WiFi.RSSI();
WiFi.scan();
WiFi.setCredentials();
```

And we can extend this to include specifics of other networks:

```
Cellular.RSSI();
Cellular.carrier();
Cellular.location();
// just examples - not proposal
```

**Comment by zsup** [comment]
:+1:

**Comment by m-mcgowan** [comment]
This has been implemented - the Electron and Core/Photon expose different network classes.
