### ISSUE TITLE
Photon - increase Wifi credentials limit/document

### ISSUE THREAD

**Issue by kennethlimcp** [spark/firmware#517]
There's no where mentioning the number of Wifi credentials allowed to be stored on a Photon. 

The answer is **5** and should at least match **7** on the core.

```
#define MAX_CREDENTIALS     5
```

https://community.particle.io/t/photon-multiple-sets-of-credentials/14070

**Comment by m-mcgowan** [comment]
I agree it's desirable they are the same on the Core and Photon, but equally this needs to be weighed up against the difficulty of actually increasing that limit on the Photon. Sadly, it's far form a trivial change, so our first step is to document that the limit is 5 on the photon.
