### ISSUE TITLE
Photon can function as a HID device

### ISSUE THREAD

**Issue by towynlin** [spark/firmware#528]
This has been discussed for a long time in the community, and it has been in progress as a low priority story for a long time. Adding this issue mostly as a place for discussion. If you want this, please add a :+1: in the comments.

**Comment by bprobbins** [comment]
:+1:

**Comment by wgbartley** [comment]
:+1: :heart:

**Comment by ScruffR** [comment]
:+1:
Especially cool would be the option to have a composite USB HID device (keyboard + mouse + serial + ...) 
A model implementation for this would be Teensy, where you can have each combination of HIDs with or without USB serial.

**Comment by WebDust21** [comment]
Oh, great...as if the Windows "serial ballpoint mouse" wasn't a big enough problem, now you can do it on purpose??  I give a thumbs up anyway :-)  :+1:

**Comment by technobly** [comment]
I'm going to add one for @rpiswag on the forums :+1:

**Comment by harrisonhjones** [comment]
:+1: Would be nice to have a macro like: 

HID_SET_TYPE(NONE)
HID_SET_TYPE(HID_MOUSE || HID_KEYBOARD) For mouse and keyboard
HID_SET_TYPE(HID_MOUSE || HID_SERIAL) for mouse and serial
... etc ...

**Comment by ScruffR** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1:  for the macro idea

**Comment by rfresh737** [comment]
Mouse.moveTo() absolute positioning would be a very welcome feature.

**Comment by hramadan** [comment]
Ten thumbs up from me! Is it possible to get an ETA for a firmware release? Am sure that I am not the only one hanging out for this feature......

**Comment by greg5678** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: for the macro idea! Please!

**Comment by jtzemp** [comment]
Is it possible just to have a small, lightweight shim in the firmware and to have the bulk of the implementation in an external library? I'm still pretty noobish when it comes to firmware-land, but I do have interest in doing some HID-related stuff. I'm mostly just thinking about taking up space on the device for a `Mouse` and `Keyboard` library that would only get used in a fraction of the cases where people are using Photons (and Electrons, I suppose since it uses the same MCU).

**Comment by ScruffR** [comment]
I'd be happy if it was an extra library too, but AFAIK things like this won't be linked into the BIN if not used anyway.

**Comment by hramadan** [comment]
When enabling multiple USB device types, it would be nice to only enable the ones you want at *runtime* so that only the devices you are going to use end up in the PC's device list. This allows the USB device types to be selected by the user via config or command.

**Comment by m-mcgowan** [comment]
Totally JT. Any significant functionality is best pushed out to a library if the technical constraints allow that. (I did the same with FreeRTOS on the core - a few shims in firmware and the bulk of the freertos code available as a library.)

**Comment by bymaximus** [comment]
Forecast? :+1:

**Comment by naikrovek** [comment]
:+1: this would be very handy for me.

**Comment by NGenetzky** [comment]
I think this would be very helpful.

**Comment by amcchord** [comment]
:+1:

**Comment by Holmser** [comment]
:+1:

**Comment by jango-fx** [comment]
so is this working now?
is there any documentation of it??

**Comment by ScruffR** [comment]
Yes it is, but only for the STM32F2 devices Photon/P1/Electron and not for the STM32F1 Core

**Comment by jango-fx** [comment]
and how?

**Comment by hramadan** [comment]
@jango-fx, the following should help:

https://community.particle.io/t/solved-0-6-0-rc2-keyboard-press-how-to/25704

**Comment by jango-fx** [comment]
all I get is
`error: 'Keyboard' was not declared in this scope`

**Comment by hramadan** [comment]
@jango-fx, how are you compiling, with the Web IDE?

#include "application.h"

**Comment by ScruffR** [comment]
I guess this discussion should not be lead in the comments section of the issue.
@jango-fx, you can open a new thread at https://community.particle.io or post a reply on the topic linked above.

**Comment by jango-fx** [comment]
hm, didn't find that thread during my research... switched to the forum. thx so far.
