### ISSUE TITLE
Firmware flash script has a typo

### ISSUE THREAD

**Issue by jonbgallant** [spark/firmware#559]
This page https://github.com/spark/firmware/releases/tag/v0.4.4 should have this code "without the v prefix before the version number"

https://gist.githubusercontent.com/jonbgallant/4ac59884183611790ea7/raw/a9a213477a1314731a1a65932bf556c75f12fa1c/photonflash.cmd

**Comment by m-mcgowan** [comment]
Fixed, thanks for reporting!
