### ISSUE TITLE
[Photon] `WiFi.setCredentials` only works for networks currently in range?

### ISSUE THREAD

**Issue by pomplesiegel** [spark/firmware#574]
While Photon was connected to our office network, I called `WiFI.setCredentials()` to hard-code a customer's WiFi creds into it before it went to the customer's home. 

Following `setCredentials` our code running in `SYSTEM_MODE(MANUAL)` calls 

````cpp
  WiFi.off();
  delay(500);
  WiFi.on();
  WiFi.connect();
  Spark.connect();
````

At this point it disconnects (flashing green), then connects back to the office network (still stored), as the new customer creds do not represent a network currently in range.

However, when the Photon was put in range of the customer's AP, it still did not connect (instead flashing green). When the customer mimicked our office network using an iPhone hotspot and I again called  `WiFI.setCredentials()`with the network in range, it successfully connected to the customer's AP. 

Does the Photon ignore/erase creds if they do not work upon the first try?

**Comment by m-mcgowan** [comment]
Yes, just as for the other issue with hidden networks -  `setCredentials()` must be able to scan the network to obtain all of the network details.

It would be possible to extend `setCredentials()` so that these details are passed in as part of the function call. Would that help?

**Comment by pomplesiegel** [comment]
Sure, that would help! This is mainly crucial on a dev level, before we have the soft-ap migration API integrated into an app.

**Comment by m-mcgowan** [comment]
If you pull `develop` you'll be able to call
```
 WiFi.setCredentials("ssid)",4,"password", 8, WPA2, WLAN_CIPHER_AES);
```
Which doesn't scan the network to find the cipher, so the AP can be added offline.

**Comment by pomplesiegel** [comment]
@m-mcgowan, this passed w/ flying colors on a real test. Thanks!

**Comment by m-mcgowan** [comment]
Cool. Thanks for confirming!
