### ISSUE TITLE
Unexpected interrupt when calling attachInterrupt()

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#585]
I had a slack discussion with Satish about this topic
 http://community.particle.io/t/internally-pulled-up-interrupt-issue-and-work-around/14717

My impression after previously testing on the Core was, that you could have the pins as OUTPUT or INPUT with "correct" or "opposite" pull-resistors and the interrupt just worked as expected (no unintended/premature firing).

I had no way of testing the OPs problem (due to particle-less vacation), but if his observation is true, it looks like a regression from the behaviour of Core w/ 0.3.4.

There was some discussion between Paul and me a while back about this, where Paul put me right on the (previous) fact that `attachInterrupt()` does ***not*** mess with pin mode and pull-resistors. 
 http://community.particle.io/t/having-trouble-using-sleep-with-wakeuppin/10691/16

But as the OP reports, that seems to have changed on the Photon (for the worse).

**Comment by m-mcgowan** [comment]
OP reports this is now suddenly working, so closing out.
