### ISSUE TITLE
Serial.flush() is an empty function

### ISSUE THREAD

**Issue by pkourany** [spark/firmware#600]
Serial.flush() is an empty function and does nothing unlike the USART-based Serial1 and Serial2 flush functions.  Flush needs to wait for all OUTGOING data to complete before returning.  Either code is added to the function or the docs are changed to reflect that Serial.flush() does nothing.

**Comment by m-mcgowan** [comment]
I think it is empty for good reason - the system will hang if there is no serial reader on the PC consuming the data. Please see the PR above for code that implements the flush() on a photon and a test app.
