### ISSUE TITLE
Adding WiFi networks from code

### ISSUE THREAD

**Issue by jenesaisdiq** [spark/firmware#617]
I frequently move multiple devices from one network to another, and often know the next network's creds before I move them. Would be great to expose a function to add networks from firmware; I could then create a `Particle.subscribe` to preset the new WiFi on all those devices. Would save needing physical access to the Photon inside the device, and repeating the setup process over and over.

**Comment by m-mcgowan** [comment]
We have the `WiFi.setCredentials()` API which adds a new access point. Does that address the need here?

**Comment by jenesaisdiq** [comment]
Dammit Mat, already ahead of me! Thanks!
