### ISSUE TITLE
stat: cannot stat '../../../build/target/system-part1/platform-6-m/system-part1.bin.pre_crc'

### ISSUE THREAD

**Issue by fritjof** [spark/firmware#627]
Hello,

After checking out branch "latest" I still get compile errors on missing files. Any ideas?

~/particle/firmware/modules$ make clean all PLATFORM=photon -s
clean all
stat: cannot stat '../../../build/target/system-part1/platform-6-m/system-part1.bin.pre_crc': No such file or directory
stat: cannot stat '../../../build/target/system-part1/platform-6-m/system-part1.bin.pre_crc': No such file or directory
head: cannot open '../../../build/target/system-part1/platform-6-m/system-part1.bin.pre_crc' for reading: No such file or directory
head: cannot open '../../../build/target/system-part1/platform-6-m/system-part1.bin.pre_crc' for reading: No such file or directory
   text	   data	    bss	    dec	    hex	filename
 248904	    144	     40	 249088	  3cd00	../../../build/target/system-part1/platform-6-m/system-part1.elf
stat: cannot stat '../../../build/target/system-part2/platform-6-m/system-part2.bin.pre_crc': No such file or directory
stat: cannot stat '../../../build/target/system-part2/platform-6-m/system-part2.bin.pre_crc': No such file or directory
head: cannot open '../../../build/target/system-part2/platform-6-m/system-part2.bin.pre_crc' for reading: No such file or directory
head: cannot open '../../../build/target/system-part2/platform-6-m/system-part2.bin.pre_crc' for reading: No such file or directory
   text	   data	    bss	    dec	    hex	filename
 161668	   2180	  38260	 202108	  3157c	../../../build/target/system-part2/platform-6-m/system-part2.elf
stat: cannot stat '../../../build/target/user-part/platform-6-m/user-part.bin.pre_crc': No such file or directory
stat: cannot stat '../../../build/target/user-part/platform-6-m/user-part.bin.pre_crc': No such file or directory
head: cannot open '../../../build/target/user-part/platform-6-m/user-part.bin.pre_crc' for reading: No such file or directory
head: cannot open '../../../build/target/user-part/platform-6-m/user-part.bin.pre_crc' for reading: No such file or directory
   text	   data	    bss	    dec	    hex	filename
   4836	    152	    348	   5336	   14d8	../../../build/target/user-part/platform-6-m/user-part.elf

**Comment by m-mcgowan** [comment]
I think the forum is probably the right place for this question. Leave off the `-s` to get more detail and post the result to the forum. Thanks!
