### ISSUE TITLE
Pure virtual call on creation of low priority std::thread

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#652]
Creating an `std::thread` with priority lower or equal to the priority of the current thread results in a pure virtual call that crashes the device. This may manifests itself during creation of the `SystemThread` with `SYSTEM_THREAD(ENABLED)`.

**It will not happen on firmware 0.4.6 because of a workaround that ensures std::thread are created with a high enough priority.**

The constructor of `std::thread` is:

```c++
    struct _Impl_base
    {
      __shared_base_type	_M_this_ptr;
      inline virtual ~_Impl_base();
      virtual void _M_run() = 0;
    };

    typedef shared_ptr<_Impl_base>	__shared_base_type;

    template<typename _Callable, typename... _Args>
      explicit 
      thread(_Callable&& __f, _Args&&... __args)
      {
        _M_start_thread(_M_make_routine(std::__bind_simple(
                std::forward<_Callable>(__f),
                std::forward<_Args>(__args)...)));
      }
```

[`thread::_M_start_thread`](https://github.com/spark/firmware/blob/7252cb80a9dbbd6da6f9f9a3294f1af681ffe06e/system/src/system_threading.cpp#L73) creates a FreeRTOS thread with a certain priority.

```
    void thread::_M_start_thread(thread::__shared_base_type base)
    {
        if (os_thread_create(&_M_id._M_thread, "std::thread", OS_THREAD_PRIORITY_DEFAULT, invoke_thread, base.get(), 1024*20)) {
            PANIC(AssertionFailure, "%s %s", __FILE__, __LINE__);
        }
    }
```

If the priority is 2 or less, the current thread is not preempted when the new thread is created since the WICED app_thread has priority 2. `_M_start_thread` passes the shared pointer to the functor `base.get()` as the RTOS thread creation param.

`thread::_M_start_thread` then returns, the shared pointer count is decreased by one so the `std::thread` constructor destroys the functor `base`.

When `invoke_thread` is called, the functor is blank, leading to the pure virtual call of `_M_run`.

```c++
    void invoke_thread(void* ptr)
    {
        thread::_Impl_base* call = (thread::_Impl_base*)ptr;
        call->_M_run();
    }
```

It looks like there's a missing operation to increase the reference count of the shared pointer `base` inside `thread::_M_start_thread` and that the shared pointer should be passed to `invoke_thread` instead of the raw pointer.

(This is my interpretation, some of this may be wildly inaccurate).

**Comment by m-mcgowan** [comment]
Thank you for this. I looked at it yesterday, but couldn't formulate a theory of the problem. It does sound like there is an incorrect use of shared pointers - since each client should have their own reference, whereas currently the only reference created is the one in `_M_start_thread()` from the shared pointer passed via copy, which could be deallocated before the created thread has time to start.


The simplest solution is to increment the reference to the shared pointer by creating a new shared pointer referring to the same:

```
__shared_base_type thread_ref = new __shared_base_type(base);
```

and pass that as the thread creation parameter. 

`invoke_thread` then looks like this:

```
 void invoke_thread(void* ptr)
    {
        thread::__shared_base_type* shared_fn =  (thread::__shared_base_type*)ptr;
        thread::__Impl call = shared_fn->get();  // copy the function value
        delete shared_fn;    // free the shared pointer
        call._M_run();
    }
```

I'll try this out next week.
