### ISSUE TITLE
retained variables are not persisting, even without reset or deep sleep.

### ISSUE THREAD

**Issue by technobly** [spark/firmware#661]
Please see:
https://community.particle.io/t/backup-ram-not-working/16179

Just to confirm, is it correct that retained variables should come up as the last written value after a reset or deep sleep event, and not be re-initialized if declared and initialized globally?  So in the first two posts of the above thread, we have:

`retained int saveValue = 10;`

If the last written state is 500 lets say, after reset it would still be 500, yeah?

**Comment by m-mcgowan** [comment]
Strange. I woke up thinking about this and then remembered that the docs don't include the command to enable retained variables. 

```
STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY));
```

**Comment by m-mcgowan** [comment]
Docs updated.

**Comment by technobly** [comment]
Is there a reason it's not always enabled?  Since it has a keyword it's pretty unique.

**Comment by technobly** [comment]
I just tested with the enable command and not retained seems to work just like normal variables when powered, but if I reset when I'm in the 5 second delay it comes up setting the value to 10 again, instead of 15.  If I don't initialize the value, it still comes up as 0 instead of 15.

```cpp
STARTUP(System.enableFeature(FEATURE_RETAINED_MEMORY));

retained int saveValue = 10;

void setup() {
    Serial.begin(9600);
}

void loop() {
        Serial.println(saveValue);
        saveValue = 15;
        Serial.println(saveValue);
        Serial.println(saveValue);
        delay(5000);
}
```

**Comment by technobly** [comment]
Ok figured this out... thought it was ok to hard reset it (pushing the reset button) but it only retains memory with a soft reset, E.g., System.reset();

I'll update the docs with that clarification ;-)

**Comment by technobly** [comment]
Ahh, so much confuse... there was an issue with how SRAM was initialized which led to much confusion.  Fixed with this PR: https://github.com/spark/firmware/pull/664
