### ISSUE TITLE
Photon: analogWrite() for DAC requires pinMode() each time

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#662]
As in this docs issue spark/docs#170

I think this is an undesirable behaviour, that each call to analogWrite() for a DAC pin compulsory requires a preceding call to pinMode(DAC, OUTPUT).
It should rather be like with PWM pins, that one single pinMode(DAC, OUTPUT) is enough.

See test
https://community.particle.io/t/analogwrite-dac-only-once-for-each-pinmode-output/15393/2

---

*Sorry, I originally opened this issue in private firmware*

**Comment by ScruffR** [comment]
#671 makes this one look a minor glitch :-(

**Comment by m-mcgowan** [comment]
Verified working.
