### ISSUE TITLE
string.toLowerCase() has no effect on string

### ISSUE THREAD

**Issue by BracWebb** [spark/firmware#665]
Building for photon on `latest` (Release 0.4.6)
commit 830375c700e4ecd27d8c90d557e05872568d2619

string.toLowerCase() does not manipulate the string to all lower case.
string.toUpperCase() works as expected.

**Comment by m-mcgowan** [comment]
Thanks! There's a bug in toLowerCase() that only executed if the buffer was empty...and then there's no data to convert to lowercase! :-)
