### ISSUE TITLE
Clearing TX buffer in Serial

### ISSUE THREAD

**Issue by talybin** [spark/firmware#682]
I got a problem transmit over Serial1. The first char in first message is always garbage. Looking in HAL_USART_Init (https://github.com/spark/firmware/blob/develop/hal/src/core/usart_hal.c#L120) rx_buffer clears twice and there is no clear for tx_buffer which can be the reason for my problem. Suppose it is a copy-paste mistake. Please fix!

**Comment by technobly** [comment]
Nice catch, this infamous copypasta has it's own restaurant chain:

https://github.com/spark/firmware/blob/develop/hal/src/core/usart_hal.c#L215

https://github.com/spark/firmware/blob/develop/hal/src/stm32f2xx/usart_hal.c#L263-L264

https://github.com/spark/firmware/blob/develop/hal/src/stm32f2xx/usart_hal.c#L263-L264

**Comment by zerous01** [comment]
Mora pasta in

https://github.com/spark/firmware/blob/develop/hal/src/stm32f2xx/usart_hal.c#L148-L149

**Comment by m-mcgowan** [comment]
grazie! non vogliamo la pasta!

**Comment by technobly** [comment]
Oops, I see I pasted the same link twice up there instead of this one ^ which I'm sure I found before.  Thanks @zerous01 :+1: :spaghetti:

**Comment by m-mcgowan** [comment]
TX buffer cleared in 0.4.7.
