### ISSUE TITLE
HTTP library

### ISSUE THREAD

**Issue by camilstaps** [spark/firmware#768]
Are there any plans to add an HTTP library to the firmware?

**Comment by m-mcgowan** [comment]
There is already the HTTPClient library. We don't add functionality to the firmware if it can be provided as a library. Does that library meet your needs?

**Comment by camilstaps** [comment]
Yes, it does. I didn't mean to suggest to reinvent the wheel. It would however be useful to add this library or an equivalent one as a submodule here, so that people using the online IDE can easily use it as well.

**Comment by camilstaps** [comment]
Never mind, I found it. Thanks again.
