### ISSUE TITLE
Core: Building with Web IDE against "Latest (0.4.7)" fails - against "0.4.7" works???

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#769]
I've just had a member reporting problems with `Particle.xxxx` but `Spark.xxxx` worked.
After confirming he was targeting latest firmware, I tested this myself and found that this `error: 'Particle' was not declared in this scope` pops up when building against `Latest (0.4.7)` but does build fine against `0.4.7` (not Latest).

https://community.particle.io/t/particle-was-not-declared-in-this-scope/18285/4

---

The same goes for `pulseIn()` and I guess other standard libraries too.

**Comment by monkbroc** [comment]
Looks like Latest is not pointing to 0.4.7. Here's another strange compiler error because of this:
http://community.particle.io/t/random-compiler-errors-on-system-thread-enabled/18301

**Comment by monkbroc** [comment]
This is a build server issue. Dave knows about it now.

**Comment by ScruffR** [comment]
**Please update the status of this issue!**

Currently Photons should work as usual again.

On Particle Dev and CLI version selection is not available, so the only alleged way around this is to try to build over and over till you hit a working build server.

**Comment by m-mcgowan** [comment]
I understand a fix for this has been rolled out now to the compiler service.
