### ISSUE TITLE
Radio vs. Particle Network on/off

### ISSUE THREAD

**Issue by KeighDub** [spark/firmware#774]
With the device in manual mode, turning particle network on and off seems to put you in inconsistent states.

1. System Powered Up - Breathing White
2. Cellular.on() - Breathing Blue (RSSI call does not function)
3. Particle.connect() - Breathing Cyan (RSSI call functions)
4. Particle.disconnect() - Breathing Green (RSSI call functions)

Unless I misunderstand, 2 & 4 should be the same state

**Comment by m-mcgowan** [comment]
`Particle.connect()` also calls `Cellular.connect()`, so there are additional connection states not covered above.
