### ISSUE TITLE
when cloud variable is declared as float, wrong value is returned

### ISSUE THREAD

**Issue by gbrault** [spark/firmware#789]
I had a variable declared as float and the returned value was wired.
I changed the declaration to double and everything works right now.

Can you support float as well for variables?

Or chnage the documentation to warn not using float.

Thanks

**Comment by m-mcgowan** [comment]
There are many types of scalar and floating point - for simplicity we support `int` and `double` only. If you use the new `Particle.variable("name"  value)` API, the compiler will complain if you use an unsupported variable type.

**Comment by gbrault** [comment]
Thx. Just need to highlight that in the documentation then
