### ISSUE TITLE
develop branch doesn't compile for electron builds

### ISSUE THREAD

**Issue by dmiddlecamp** [spark/firmware#794]
when building with:

```
make all PLATFORM_ID=10 -s COMPILE_LTO=n DEBUG_BUILD=n PARTICLE_DEVELOP=1

...

cannot open linker script file backup_ram.ld: No such file or directory
```

(just opening temporary issue so it's on the radar).

Three lingering references to backup_ram.ld:

* build/arm/linker/linker_stm32f2xx_common.ld
* hal/src/electron/app_no_bootloader.ld
* hal/src/photon/wiced/platform/MCU/STM32F2xx/GCC/app_no_bootloader.ld

appears to need to be renamed to:

```
INCLUDE backup_ram_user.ld
OR
INCLUDE backup_ram_memory.ld
```

**Comment by m-mcgowan** [comment]
Ha, I was just about to push a fix for this then got pulled into a meeting!
