### ISSUE TITLE
Serial.availableForWrite function

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#798]
https://community.particle.io/t/serial-availableforwrite-function/18831/4

We can check if the TX buffer is full or not to allow applications to implement flow control.

**Comment by Ibuprofen** [comment]
:+1: Thanks for filing this!

**Comment by m-mcgowan** [comment]
Currently, the hardware serial devices corrupt data if fed too quickly. I feel the default should be to block until the buffer is emptied, so the application doesn't have to concern itself with how fast it writes data by default.  For most, having the correct data output is more important than writing it quickly and getting corrupted data.    For cases where performance is critical, a new method. `blockOnOverrun(false)` can be called to disable blocking, and revert to the current non-blocking behavior that overruns the buffer.

The USB serial device write function includes a delay as a simple form of flow control. Instead, it should check if the buffer would overrun and block, similarly to Serial1. One additional point is that the buffer is not emptied if no USB host is connected, so the method should block only when a host is connected. This can be detected by checking the established linerate.
