### ISSUE TITLE
SPI Slave Support in Firmware

### ISSUE THREAD

**Issue by harrisonhjones** [spark/firmware#814]
Posting here for a customer. Would like to add firmware support for using the Photon/Spark Core as a SPI slave. 

This [gist](https://gist.github.com/chrismeyersfsu/3317769) might help. It's written for the arduino. 

This [page](http://www.gammon.com.au/spi) has a bit more in-depth information. 

Feel free to discuss this feature here.

**Comment by AronRubin** [comment]
https://github.com/btmcmahan/Teensy-3.0-SPI-Master---Slave

**Comment by dseemakurty** [comment]
I would find this extremely helpful also!

**Comment by m-mcgowan** [comment]
@avtolstoy  Please add tests to verify that SPI.transfer() with a `nullptr` callback does block until the transfer is complete.

**Comment by avtolstoy** [comment]
#919 fixes SPI.transfer() behavior and adds necessary tests.
