### ISSUE TITLE
Reports that TCP::write leaks memory

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#822]
This thread discusses an observed memory leak on the Photon with TCP::write https://community.particle.io/t/tcp-client-write-function/17194

**Comment by sergeuz** [comment]
Can't reproduce this in latest "develop". As for the code provided, it seems `WebInterface` doesn't remove response data from associated hash map once response is processed: https://gist.github.com/bgenchel/b5018230a050ddfa320e#file-webinterface-h-L217, causing hash map to grow indefinitely.

**Comment by m-mcgowan** [comment]
Thanks!
