### ISSUE TITLE
analogWrite() : Taking care of the passing in parameter 'value' in the wiring function

### ISSUE THREAD

**Issue by XuGuohui** [spark/firmware#831]
Hi there,

For users using the analogWrite() API, they probably pay no attentions on the passing in parameter `value`, which range depends on the parameter `pin`. If using the pins equipped with DAC, the `value` ranges from 0 to 4095, while using the other pins equipped with timer, the `value` ranges from 0 to 255.

How about unifying the range of the passing in `value` in the HAL layer so that users just only remember  one range of the `value`, no matter which pin they want to use?

Thanks!

**Comment by m-mcgowan** [comment]
I could imagine using a `float` value from 0 to 1.0 that represents minimum and maximum output. This essentially provides resolution independent setting of an output value, whether it's digital, PWM or DAC. 

It's a nice idea having the pins consistent, but I wonder if it would cause confusion?

An alternative approach would be to log an error if the pin values are out of range.

**Comment by XuGuohui** [comment]
The first method you bringing up sounds great. 

I don't know if someone who hasn't viewed the source code knows the value range on different pin, especially using DAC. My colleague just made this mistake when output analog value on DAC pins - He passed in 255, the value he thought being the maximum value, while the LED worked nearly weakly.

**Comment by m-mcgowan** [comment]
You don't need to look at the source - the pin parameters are described in the docs - https://docs.particle.io/reference/firmware/photon/#analogwrite-pwm-

**Comment by XuGuohui** [comment]
Awesome! It describes very in detail. 

Thank you!
