### ISSUE TITLE
DAC1/2 possible problem with digitalWrite() after analogWrite() [0.4.9]

### ISSUE THREAD

**Issue by ScruffR** [spark/firmware#833]
As it seems after `analogWrite()` on a DAC pin `digitalWrite()` does not work anymore.

```cpp
SYSTEM_MODE(SEMI_AUTOMATIC)

void setup()
{
    pinMode(D7, OUTPUT);
    pinMode(A6, OUTPUT); // DAC1
    pinMode(A3, OUTPUT); // DAC2
}

int i;
void loop()
{
  if (0 <= i && i <= 4095)
  {
    analogWrite(A6, i);      // ramp up
    analogWrite(A3, 4095-i); // ramp down
  }
  else
  { // -1000..-1 lead-in LOW / 4096 .. 5000 lead-out HIGH
    digitalWrite(A6, i>0 ? HIGH : LOW );
    digitalWrite(A3, i>0 ? HIGH : LOW); 
  }
  i++;
  if (i>=5000)
  {
    i=-1000;  
    digitalWrite(D7, !digitalRead(D7));
  }
  delayMicroseconds(20);
}
```
Lead-in/lead-out don't show as expected

![dac1_0-4095](https://cloud.githubusercontent.com/assets/6604878/12531160/0730630e-c1f4-11e5-9952-8cbc49a94642.png)
![dac2_4095-0](https://cloud.githubusercontent.com/assets/6604878/12531161/0cb00668-c1f4-11e5-93b3-56eb8151baac.png)

With reduced limits 500..3495 it's obvious that the last analog value persists despite the following `digitalWrite()` attempts
![dac1_500-3495](https://cloud.githubusercontent.com/assets/6604878/12531172/2fcaee7e-c1f4-11e5-805f-b497370a620d.png)

![dac2_3495-500](https://cloud.githubusercontent.com/assets/6604878/12531174/346271e6-c1f4-11e5-803e-11e1ac67a2bc.png)

Also commenting one of the `analogWrite()` lines shows that the other `analogWrite()` on the other channel influences the commented DAC
While the DAC whos `analogWrite()` is commented should look like this
![nodac](https://cloud.githubusercontent.com/assets/6604878/12531261/0a44a972-c1f6-11e5-9e44-5d21c37dd901.png)
It looks like this for DAC1 (DAC2 active / DAC1 commented)
![dac1_nodac2](https://cloud.githubusercontent.com/assets/6604878/12531269/4f727e2a-c1f6-11e5-8d8e-f1854152f0da.png)
and for DAC2 (DAC1 active / DAC2 commented)
![dac2_nodac1](https://cloud.githubusercontent.com/assets/6604878/12531273/5f61f482-c1f6-11e5-8234-900e898f2993.png)

**Comment by m-mcgowan** [comment]
Internally the pinMode is changed to enable the DAC. Could you add a pinMode() call before digitalWrite() to see if that fixes it?

If that fixes it, I can add a check in the HAL for the current pin mode as part of digitalWrite, and if it's the DAC pinmode, change it to OUTPUT.

**Comment by ScruffR** [comment]
I had tried that but it didn't change anything. But next I'll try a `pinMode(DAC, INPUT); pinMode(DAC, OUTPUT);` combo to see if this changes anything.
