### ISSUE TITLE
spark_wiring_spi.h:115:32, "expected unqualified-id before ')' token"

### ISSUE THREAD

**Issue by Jerware** [spark/firmware#840]
The 0.4.9 firmware has an issue compiling my FastLED sketch. I get six repeated errors that say, "expected unqualified-id before ')' token in ../wiring/inc/spark_wiring_spi.h:115:32

I also get 30+ compile errors, all pointing to chipsets.h inside FastLED complaining that "mSPI was not declared in this scope." I'm hopeful these errors are due to the system SPI problem.

**Comment by m-mcgowan** [comment]
SPI was changed from a global instance to a #define to ensure that it is initialized before use. 

I'm guessing the library is defining it's own SPI symbol?
If you are not using SPI, then you can add #undef SPI before including other application headers.

**Comment by Jerware** [comment]
Thanks, you're absolutely right. I've raised the issue on the FastLED GitHub.

**Comment by m-mcgowan** [comment]
:+1:

**Comment by m-mcgowan** [comment]
Reverted the change of SPI to a macro.
