### ISSUE TITLE
Allow changing the PWM and DAC resolution

### ISSUE THREAD

**Issue by monkbroc** [spark/firmware#841]
Add analogWriteResolution to allow changing the PWM and DAC resolution from 8 bits to up to 16 bits (that many bits may not be available on the hardware).

Community post http://community.particle.io/t/photon-pwm-resolution/19395/9

See https://www.arduino.cc/en/Reference/AnalogWriteResolution for specification

**Comment by m-mcgowan** [comment]
Relates to #213, which closed when `analogWrite()` was extended to allow the frequency to be set.

**Comment by monkbroc** [comment]
I missed that #213 was asking for both resolution and frequency improvements :flushed:

**Comment by andyggraves** [comment]
Hi, everyone, not meaning to push, but was wondering what is the process / how long for an idea like this? Cheers

**Comment by BasedOnTechnology** [comment]
@m-mcgowan Echoing @andyggraves. This would be really, really helpful for me too.

**Comment by monkbroc** [comment]
I hear you. This is something I have on my list of things to do.

**Comment by BasedOnTechnology** [comment]
@monkbroc Thank you very much!

**Comment by andyggraves** [comment]
This is wonderful, thank you.
Will it become available on the web build UI?

**Comment by andyggraves** [comment]
Hi Guys, 
I am trying to use the new exciting analogueWriteResolution function but it does not seem to be recognised "particle build" where am i going wrong?
Thanks
Andy

**Comment by ScruffR** [comment]
This hasn't been merged into the release branch yet -  there are still some tasks to be completed first.
