### ISSUE TITLE
Support ARM GCC 5.x series

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#858]
When compiling with the 5.x series of ARM GCC, there are new compiler errors that don't appear with the 4.9.x series. 

@sergeuz  is investigating this.

**Comment by sergeuz** [comment]
@m-mcgowan What version of gcc and build environment did you use? I just tried gcc 5.2.1 on Ubuntu (there's PPA for it) and the firmware builds normally.

**Comment by m-mcgowan** [comment]
To be sure, please try running .\ci]enumerate_build.matrix.sh since that builds for all platforms.  I tried the Core.

**Comment by sergeuz** [comment]
ok, I've tried only Photon and Electron platforms. The build indeed fails for the Core
