### ISSUE TITLE
static checks of dynamically linked functions

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#875]
Dynamic linked functions must maintain binary compatibility from one release to the next. 

At present, any changes are evaluated as part of code review. Dynamic functions are spread throughout the codebase, requiring careful review to ensure all changes are compatible.

Some compiler-assistance here would be a good first step to preventing unintended changes. 

One possible solution is to add to each dynamic linked module a file that statically checks the function signatures of all dynamically linked functions in that module. Any changes to dynamically linked functions would then cause a compiler error, which is only mitigated by a change to the dynamic link checks, which are all in one place (for a given dynamic link module.) 

Some changes to the dynamic link interface are allowed where they preserve binary compatibility. Having these changes also updated in the dynamic link checks provides a single point of reference for reviewing the history of changes to a dynamic link interface. 

To statically detect changes, the dynamic checks could include:

- checks for the signature of each dynamic function, by checking the type and size of all arguments passed to the function, and the type and size of the return type 

- for types passed by pointer/reference, checking the size of these types

Before implementing, we should also investigate existing solutions, such as http://ispras.linuxbase.org/index.php/ABI_compliance_checker

**Comment by sergeuz** [comment]
`abi-compliance-checker` that you mentioned seems to be the most versatile and configurable tool among ones that I've managed to try or google about. I checked it on a number of ABI-breaking scenarios and it worked perfectly well. The only disadvantage of this and similar tools is that they need to be integrated into our build process (thus introducing additional dependency) and require object dumps (some text data, typically) to be stored under version control system and updated every time API of some dynamically invoked module is changed.

Alternative (or complementary) approach is to add some compile-time checks, e.g. updating our `DYNALIB_FN` definition:
```
template<typename T1, typename T2>
constexpr const void* checkFunctionType(T2 *func) {
    static_assert(std::is_same<T1, T2>::value, "Function signature has changed");
    return (const void*)func;
}

#define DYNALIB_FN(tablename, name, type) \
    checkFunctionType<type>(name),

// ...

DYNALIB_BEGIN(hal_gpio)
DYNALIB_FN(hal_gpio, HAL_GPIO_Write, void (pin_t, uint8_t))
DYNALIB_FN(hal_gpio, HAL_GPIO_Read, int32_t (pin_t))
DYNALIB_END(hal_gpio)
```

While above check can't catch incompatible changes of typedef'ed types or sizes of structures passed by reference or pointer, it's easy to implement and it works well for some typical cases we observe during code review.
