### ISSUE TITLE
Expose FreeRTOS xTimerIsTimerActive() for Software Timers

### ISSUE THREAD

**Issue by pkourany** [spark/firmware#920]
By exposing the FreeRTOS xTimerIsTimerActive() function, a user can query a timer to get its running state.

**Comment by m-mcgowan** [comment]
What's the use case for this @pkourany?

For a high-level API, how about

```
Timer myTimer;

bool active = myTimer.isActive();

```

**Comment by pkourany** [comment]
@m-mcgowan, here is a use case:

https://community.particle.io/t/a-new-method-for-switch-debounce-comments-please/21333

Your suggested API is perfect.
