### ISSUE TITLE
[CORE] Error writing firmware…Incorrect platform id

### ISSUE THREAD

**Issue by MaxSharx** [spark/firmware#928]
Referencing: https://community.particle.io/t/core-error-writing-firmware-incorrect-platform-id/21229

> Error writing firmware...Incorrect platform id (expected 0, parsed 60769)

Is there any chance to get rid of that message finally?

Regards,
Marcus

**Comment by m-mcgowan** [comment]
I reproduced the issue. Binary Version Reader returns the correct details, so I'm puzzled how the CLI is getting the wrong version. (btw, @monkbroc, the CLI repo would have been a better home for this issue since it's not a firmware bug.)

**Comment by technobly** [comment]
Added to CLI repo here: https://github.com/spark/particle-cli/issues/232
