### ISSUE TITLE
isascii not declared in this scope

### ISSUE THREAD

**Issue by mikey0000** [spark/firmware#963]
< Please summarize your issue here.  Check [x] as many boxes below as you can before submitting your issue.  Thanks -- you rock! >

On macOSX El Capitan with gcc-arm-none-eabi-5_3-2016q1 I am getting the error 
`../wiring/inc/spark_wiring_character.h:49:31: error: 'isascii' was not declared in this scope`
`/wiring/inc/spark_wiring_character.h:104:21: error: 'toascii' was not declared in this scope`
running make clean all
---

Completeness:
- [ x] Minimum test case added
- [ x] Device, system and user firmware versions stated
- [x] Particle confirmed

**Comment by kunbo** [comment]
I also get the issue, how I can fix it?

**Comment by m-mcgowan** [comment]
You can pull in the pull request linked above which contains the fix.
