### ISSUE TITLE
Suggest adding Time.uptime()

### ISSUE THREAD

**Issue by andyw-lala** [spark/firmware#967]
Most of the examples in the forums that claim to report/monitor uptime, are actually just reporting Time.now().

While you can monitor the event stream to pick up device online events, and there is movement on the restart syndrome front, having a simple unsigned integer to report in publish messages that is maintained by the clock/time subsystem and consistent with other time values would be valuable, IMO.

Putting the requirement out there for discussion first.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated (as of 0.6.0)

**Comment by monkbroc** [comment]
How would that be different than `millis()`?

**Comment by andyw-lala** [comment]
Resolution and rollover time ?

**Comment by andyw-lala** [comment]
If millis() were uint64_t, I'd use that / 1000. But sadly, it is not.

**Comment by technobly** [comment]
millis() wraps after about 50 days... that's a good long up time, but I can see the advantage of another uint64_t counter that's 50*50 days.  systick that updates millis() behind the scenes could easily manage this.

**Comment by m-mcgowan** [comment]
`System.uptime()` added with https://github.com/spark/firmware/pull/1393
