### ISSUE TITLE
Centralize system status LED updates

### ISSUE THREAD

**Issue by m-mcgowan** [spark/firmware#976]
Currently, the system status LED is controlled in many places throughout system firmware, making this single feature difficult to test and debug.  A cleaner design would use system events as a source of notifications of all the relevant system state changes and update the LED color/pattern based on the current event. This allows all the LED handling code to exist in a single block. This will make the LED handling easier to test and maintain.

Note that this is orthogonal to #569, which allows multiple clients to use the LED.  Even with #569 implemented, the LED handling in the system firmware would still be spread throughout.

Implementation note: since we have some LED handling already done on the SysTick interrupt, it makes sense to move all LED handling there, with the LED color set from system state. This would consolidate all the LED updates in system firmware.

---

Completeness:
- [x] Minimum test case added
- [x] Device, system and user firmware versions stated

**Comment by technobly** [comment]
Implemented in PR #1205
